#! /bin/sh

set -e
#set -x

CLASSPATH=$CLASSPATH:/export/scratch1/jong/glt/asfsdf-meta/trunk/build/meta/gui/lib/idw-gpl-1.3.0.jar
CLASSPATH=$CLASSPATH:/export/scratch1/jong/glt/asfsdf-meta/trunk/build/meta/gui/data
CLASSPATH=$CLASSPATH:/export/scratch1/jong/glt/asfsdf-meta/trunk/build/meta/gui/studio
CLASSPATH=$CLASSPATH:/export/scratch1/jong/glt/asfsdf-meta/trunk/build/meta/gui/util
CLASSPATH=$CLASSPATH:`toolbus-java-adapter-config`
export CLASSPATH

/export/scratch1/jong/java/current/bin/java nl.cwi.sen1.gui.BasicStudio $@
