/**
 * This file is generated by tifstoc. Do not edit!
 * Generated from tifs for tool 'extract-sdf' (prefix='')
 */

#include "extract-sdf.h"

#define NR_SIG_ENTRIES	2

static char *signature[NR_SIG_ENTRIES] = {
  "rec-eval(<extract-sdf>,normalize(<term>))",
  "rec-terminate(<extract-sdf>,<term>)",
};

/* Event handler for tool 'extract-sdf' */
ATerm extract_sdf_handler(int conn, ATerm term)
{
  ATerm in, out;
  /* We need some temporary variables during matching */
  ATerm t0;

  if(ATmatch(term, "rec-eval(normalize(<term>))", &t0)) {
    return normalize(conn, t0);
  }
  if(ATmatch(term, "rec-terminate(<term>)", &t0)) {
    rec_terminate(conn, t0);
    return NULL;
  }
  if(ATmatch(term, "rec-do(signature(<term>,<term>))", &in, &out)) {
    ATerm result = extract_sdf_checker(conn, in);
    if(!ATmatch(result, "[]"))
      ATfprintf(stderr, "warning: not in input signature:\n\t%\n\tl\n", result);
    return NULL;
  }

  ATerror("tool extract-sdf cannot handle term %t", term);
  return NULL; /* Silence the compiler */
}

/* Check the signature of the tool 'extract-sdf' */
ATerm extract_sdf_checker(int conn, ATerm siglist)
{
  return ATBcheckSignature(siglist, signature, NR_SIG_ENTRIES);
}

