=head1 NAME

Graph-browser - a user interface for the meta-environment

=head1 SYNOPSIS

B<graph-browser> (note that it is not a stand-alone component)

=head1 DESCRIPTION

The B<graph-browser> presents the I<import graph> of the specification to the 
user. Clicking on the nodes in this graph pops up a menu in which the 
I<editors> for terms, syntax, and equations can be invoked. 
Furthermore the L<AsfSdfCompiler> can be invoked via the nodes. 
For modules a file browser is available to select the modules to be 
processed. It also offers functionality to save and revert modules. 

=head1 USAGE

The graph-browser is started automatically when the meta-environment is 
started.

=head1 REFERENCES

=for docbook
	Meta-Environment: <http://www.cwi.nl/projects/MetaEnv/>
	GraphViz: <http://www.research.att.com/sw/tools/graphviz/>

=for html
	<A HREF="http://www.cwi.nl/projects/MetaEnv/">Meta-Environment</A>
	<A HREF="http://www.research.att.com/sw/tools/graphviz/">GraphViz</A>

=for mf
	Meta-Environment: <http://www.cwi.nl/projects/MetaEnv/>
	GraphViz: <http://www.research.att.com/sw/tools/graphviz/>

=for man
	Meta-Environment: <http://www.cwi.nl/projects/MetaEnv/>
	GraphViz: <http://www.research.att.com/sw/tools/graphviz/>

=for text
	Meta-Environment: <http://www.cwi.nl/projects/MetaEnv/>
	GraphViz: <http://www.research.att.com/sw/tools/graphviz/>

=head1 KNOWN BUGS

The Alt-letter shortcuts to invoke the menus do not work on several 
platforms (SGI, Sparc, Linux). 

=head1 AUTHOR

Leon Moonen <S<leon@cwi.nl>>

