repositories:
  -
   type: subversion
   protocol: svn+ssh
   location: svn.cwi.nl
   components:
    - asc-support
    - apigen
    - asf
    - asf-library
    - asfsdf-fragment
    - asfsdf-meta
    - asfsdf-meta-eclipse-imp
    - asfsdf-meta-mac-osx-bundle
    - asfsdf-plugin
    - asfsdf-fragment
    - asf-support
    - aterm
    - aterm-java
    - aterm-xml
    - balanced-binary-aterms
    - c-library
    - config-manager
    - config-support
    - config-support-java
    - console-grabber
    - console-gui
    - defacto
    - dialog-gui
    - editor-manager
    - editor-plugin
    - error-gui
    - error-support
    - error-support-java
    - graph-gui
    - graph-support
    - graph-support-java
    - io-support
    - io-support-java
    - java-meta
    - java-source-analysis
    - JJTraveler
    - JRelCal
    - meta
    - meta-autotools
    - meta-build-env
    - meta-eclipse-imp
    - meta-javatools
    - meta-doc
    - meta-studio
    - meta-update-site
    - mingw-patches
    - mod-toolbus
    - module-details-gui
    - module-manager
    - module-support-java
    - navigator-gui
    - pandora
    - pdb-shared
    - pgen
    - progress-gui
    - pt-support
    - pt-support-java
    - ptable-support
    - rascal
    - rascal-eclipse
    - rascal-plugin
    - rascal-grammar
    - rascal-fragment
    - rascal-feature
    - relational-aterms
    - rstore-support
    - rstore-support-java
    - rstore-container
    - rscript
    - rscript-meta
    - sdf
    - sdf-apigen
    - sdf-meta
    - sdf-metrics
    - sdf-support
    - sdf-library
    - sdf-pretty
    - sglr
    - sglr-invoker
    - shared-objects
    - sisyphus
    - structure-editor
    - svg-gui
    - svg-support
    - term-store
    - tide
    - tide-support
    - tifsto
    - toolbus
    - toolbuslib
    - toolbus-demos
    - toolbus-java-adapter
    - toolbus-ng
    - toolbus-ng-eclipse-imp
    - toolbus-wish-adapter
    - tunit
    - vis-base
    - vis-plugin
    - vis-plugin-generic
    - vis-plugin-generic-imp
    - vis-plugin-charts
    - vis-plugin-charts-imp
    - vis-plugin-graph
    - vis-plugin-graph-imp
    - waebric
externals: [graphviz, ruby, subversion, rubygems]
