#!/bin/sh
# $Id$

VERBOSE=1
ERROR=0

cd `dirname $0`;
mydir=`pwd`

RM=rm
SGLR="sglr"
COMPARE="$mydir/trmdiff"

languages=$mydir/lang-types
tables=$mydir/tables
first=$mydir/first
terms=$mydir/terms
errterms=$mydir/erroneous

extensions=`egrep -v '^#' $languages |cut -f1`

Notify () {
	if [ $VERBOSE -gt 0 ]
	then
		echo $*                                   >&2
	fi
}

for ext in $extensions
do
	files=`ls $first/*.$ext $terms/*.$ext 2>/dev/null`
	errfiles=`ls $errterms/*.$ext 2>/dev/null`
	lang=`egrep "^$ext( |	)" $languages | cut -f2`
	ptbl=$tables/$lang.tbl

        for file in $files
        do
		base=`basename $file`
		dir=`dirname $file`
		out=$dir/`basename $base .$ext`.asfix2
		if [ ! -f $out.org ] ; then
			Notify "No reference term for $base"
			continue
		fi
		if $SGLR -p $ptbl -i $file -o $out
		then
	                if $COMPARE $out $out.org	> /dev/null
	                then
				Notify "Regression test for valid term $base succeeded"
		                ${RM} -f $out
			else
				Notify "Regression test for valid term $base failed"
				ERROR=1
	                fi
		else
			echo "Error parsing $file"	>&2
			ERROR=1
		fi
	done

        for file in $errfiles
        do
		base=`basename $file`
		dir=`dirname $file`
		out=$dir/`basename $base .$ext`.asfix2
		$SGLR --cycle -p $ptbl -i $file -o $out	2>/dev/null
	        if $COMPARE $out $out.org		> /dev/null
	        then
			Notify "Regression test for error term $base succeeded"
		        ${RM} -f $out
	        else
			Notify "Regression test for error term $base failed"
			ERROR=1
	        fi
	done
done

exit $ERROR
