#!/bin/sh
# $Id$

VERBOSE=1

cd `dirname $0`;
mydir=`pwd`

COMPARE="$mydir/trmdiff"

reference=$mydir/tables
dirs="first grammars"

Notify () {
	if [ $VERBOSE -gt 0 ] ; then
		echo $*                                   	>&2
	fi
}

RegressGenTable () {
	ptbl=`basename $1 .sdf2`.tbl
	if [ ! -f $reference/$ptbl ] ; then
		Notify "No reference table for $ptbl"
		continue
	fi
	if sdf2table $1 ; then
		diffs=1
		if [ `wc -c < $ptbl` -eq `wc -c < $reference/$ptbl` ] ; then
	        	Notify Comparing $ptbl...
	                if $COMPARE $ptbl $reference/$ptbl	>/dev/null 2>&1
	                then
		                Notify "Regress test for $1 succeeded"
		                rm -f $ptbl
			        diffs=0
	                fi
		fi
		if [ $diffs -ne 0 ] ; then
		        Notify "Regress test for $1 failed"
	        fi
	else
		Notify "Failed to generate parse table for $1"
		exit 1
	fi
}


for dir in $dirs
do
	cd $dir
        for stx in *.sdf2 ; do
	        RegressGenTable $stx
        done
	rm -f *.asfix[12]
	cd ..
done
