#! /bin/sh
# $Id$

new=/tmp/$$.new
old=/tmp/$$.old

trap 'rm -f $new $old' 0 1

for f in $@
do
	if [ -f $f -a -f $f.org ] ; then
		trmcat $f | perl -pe 's|appl|\nappl|g'		> $new;
		trmcat $f.org | perl -pe 's|appl|\nappl|g'	> $old;
		echo "Diffin' for $f..."
		diff $new $old
	fi
done
