/**
 * This file is generated by tifstoc. Do not edit!
 * Generated from tifs for tool 'layoutgraph' (prefix='')
 * Headerfile generated at Thu Jul  3 12:28:41 2003
 */

#ifndef _LAYOUTGRAPH_H
#define _LAYOUTGRAPH_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
ATerm layout_graph(int conn, ATerm);
void rec_terminate(int conn, ATerm);
extern ATerm layoutgraph_handler(int conn, ATerm term);
extern ATerm layoutgraph_checker(int conn, ATerm sigs);

#endif
