#!/bin/sh
#
#    ToolBus -- The ToolBus Application Architecture
#    Copyright (C) 1998-2000  Stichting Mathematisch Centrum, Amsterdam, 
#                             The  Netherlands.
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
if test x$1 = x
then
  NAME=Vince
else
  NAME=$1
fi

if test x$2 = x
then
  HOST=""
else
  HOST="-TB_HOST $2"
fi

if test x$3 = x
then
  PORT=""
else
  PORT="-TB_PORT $3"
fi

wish-adapter $HOST $PORT -TB_TOOL_NAME bidder -script bidder.tcl -script-args -name $NAME