/**
 * This file is generated by tifstoc. Do not edit!
 * Generated from tifs for tool 'error-support' (prefix='')
 * Headerfile generated at Thu Jan 29 17:57:27 2004
 */

#ifndef _ERROR_SUPPORT_H
#define _ERROR_SUPPORT_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
ATerm get_feedback_identification(int conn, ATerm);
ATerm get_feedback_subjects(int conn, ATerm);
ATerm get_feedback_producer(int conn, ATerm);
ATerm get_first_error_location(int conn, ATerm);
ATerm convert_feedback(int conn, ATerm);
ATerm get_first_error_description(int conn, ATerm);
void rec_terminate(int conn, ATerm);
extern ATerm error_support_handler(int conn, ATerm term);
extern ATerm error_support_checker(int conn, ATerm sigs);

#endif
