#! /bin/sh

DESC="AddressBook Service"

case "$1" in
  'start')
    echo -n "Starting $DESC: "
    CLASSPATH=../.. rmiregistry &
    echo -n "rmiregistry "
    ./abd
    echo "abd."
  ;;

  'stop')
    echo -n "Stopping $DESC: "

    pkill rmiregistry >& /dev/null
    echo -n "rmiregistry "

    PROCS=`/bin/ps x \
      | grep 'casestudy.rmi.AddressBookServer' | grep -v grep \
      | awk '{print $1}'`

    if [ "x$PROCS" != "x" ]; then
      kill $PROCS >& /dev/null
    fi
    echo "abd."
  ;;

  'restart')
    sh $0 stop
    sleep 1
    sh $0 start
  ;;

  *)
    echo "Usage: addressbook-server {start|stop|restart}" >&2
    exit 1
  ;;

esac

exit 0
