#! /bin/sh
#
# $Id$
#
# For each individual package in the Asf+Sdf Meta-Environment
# distribution that is controlled by automake, run "reconf" for
# that package prior to "configure".

aclocal -I ./config
autoconf
autoheader
automake -a
