/**
 * This file is generated by tifstoc. Do not edit!
 * Generated from tifs for tool 'clock' (prefix='')
 */

#ifndef _CLOCK_H
#define _CLOCK_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
ATerm readTime(int conn);
void rec_terminate(int conn, ATerm);
extern ATerm clock_handler(int conn, ATerm term);
extern ATerm clock_checker(int conn, ATerm sigs);

#endif
