=head1 NAME

ASFIX2C - generate C code given the AsFix representation of a specification produced via the old ASF+SDF Meta-Environment.

=head1 SYNOPSIS

B<asfix2c> [-B<h>] [-B<i> I<file>] [-B<c> I<directory>] [-B<vV>] file0 ...

=head1 DESCRIPTION

B<asfix2c> reads AsFix representations of modules, reshuffles the equations, and
generates C code for each function. The "I<meta.conf>" is used to obtain
all imported modules. 

A number of options can be supplied; these are as follows:

=over 4

=item -B<h>

Displays concise usage information.

=item -B<i> I<file>

Read input from F<file>; by default, input is either read from stdin,
or from the named files supplied as arguments.

=item -B<c> I<directory>
Write the generated auxilary AsFix files and C files in this directory
as well as the Makefiles.

=item B<-v>

Operate in verbose mode.

=item B<-V>

Yields the version number.

=back

=head1 USAGE

=head1 EXAMPLES

    $ asfix2c -i AsFix2C -c c-source

=head1 EXIT STATUS

=head1 SEE ALSO

=head1 KNOWN BUGS

=head1 NOTES

This tool will become obsolete in the near future if the old ASF+SDF 
Meta-Environment is no longer needed to develop ASF+SDF specifications.

=head1 AUTHOR

Mark van den Brand <S<Mark.van.den.Brand@cwi.nl>>
