#
# \file 
#
# This Makefile provides support for compiling Meta-Environment 
# packages in a standard way 
#
#

# Put very common CPPFLAGS, LDADD here, INCLUDES also here 
# because of pkgconfig:
AM_CPPFLAGS = 
LDADD = 

SUFFIXES =
CLEANFILES = 

pkgconfigdir  = $(libdir)/pkgconfig
docdatadir    = $(datadir)/doc/$(PACKAGE)

if MAINTAINER_MODE

SUFFIXES += .eqs .adt .idef

# Make rules for ASF programs
#%.eqs : Makefile
#	eqs-dump -m ${TOP_MODULE} -o $@
#
#%.c : %.eqs
#	asfc -i $< -o $@ -v $(ASFC_FLAGS) 
#
# Making an SDF definition
#%.def : Makefile
#	@(echo "definition" ; cat $(SDF_MODULES)) > $@
#
# Generating an ADT from an SDF definition
#%.adt : %.def
#	sdf2-to-adt --imploded --input $< --name $* 
#
# Generating a jar from an ADT
#%.jar : %.adt Makefile
#	adt-to-jave --input $< --version ${VERSION} --name $* --output .
#	mv $*-${VERSION}.jar $*.jar

# Generating C code from an ADT
#%.c %.h : %.adt Makefile
#	adt-to-c --input $< --prefix ${API_PREFIX} --output $*
#	indent $*.h
#	indent $*.c

# Generating ToolBus interfaces
#%.c %.h : %.idef Makefile
#	toolbus -gentifs $<
#	tifstoc -tool ${TOOLNAME} -tifs $*.tifs
endif

