#
# \file 
#
# This Makefile provides support for compiling Meta-Environment 
# packages in a standard way 
#
#

# Put very common CPPFLAGS, LDADD here, INCLUDES also here 
# because of pkgconfig:
AM_CPPFLAGS = 
LDADD = 

SUFFIXES =

pkgconfigdir  = $(libdir)/pkgconfig
docdatadir    = $(datadir)/doc/$(PACKAGE)


if MAINTAINER_MODE

#
# Make rules for ASF programs
#

ASFC = asfc
SUFFIXES += .eqs

.eqs.c :
	$(ASFC) -i $< -o $@ -v $(ASFC_FLAGS) 

endif

