#! /bin/sh

set -e

TABLE=/home/paulk/research/relation-calculus/Rstore.trm.tbl
RSTORE=/home/paulk/research/relation-calculus/Rstore
RESULT=result.rstore

echo -n "creating empty ${RESULT} .."
echo "rstore()" | sglr -p ${TABLE} -o ${RESULT}
echo " done."

for f in $*; do
  echo -n "merging $f into ${RESULT} .."
  $RSTORE -f merge-rstores -r RSTORE -i $f -i ${RESULT} -o ${RESULT}
  echo " done."
done

ls -l ${RESULT}
