#! /bin/sh

DESC="AddressBook Service"

case "$1" in
  'start')
    echo -n "Starting $DESC: "
    rmiregistry &
    echo -n "rmiregistry "
    ./abd
    echo "abd."
  ;;

  'stop')
    echo -n "Stopping $DESC: "

    pkill rmiregistry
    echo -n "rmiregistry "

    PROCS=`/bin/ps x \
      | grep 'java AddressBookServer' | grep -v grep \
      | cut -d' ' -f1`

    if [ "x$PROCS" != "x" ]; then
      kill $PROCS
    fi
    echo "abd."
  ;;

  'restart')
    sh $0 stop
    sleep 1
    sh $0 start
  ;;

  *)
    echo "Usage: addressbook-server {start|stop|restart}" >&2
    exit 1
  ;;

esac

exit 0
