#!/bin/sh
PROGRAM="python"

usage="$0 -TB_TOOL_NAME <name> -TB_HOST <host> -TB_PORT <port> -TB_TOOL_ID <tid> -TB_VERBOSE -script <script> -program <prog>"

while :
do
	case "$1" in
		-TB_TOOL_NAME)	NAME="-TB_TOOL_NAME $2" ;shift;shift
				;;
		-TB_HOST)	HOST="-TB_HOST $2" ;shift;shift
				;;
		-TB_PORT)	PORT="-TB_PORT $2" ;shift;shift
				;;
		-TB_TOOL_ID)	TID="-TB_TOOL_ID $2" ;shift;shift
				;;
		-TB_VERBOSE)	VERBOSE="-TB_VERBOSE" ;shift
				;;
		-TB_DEBUGPORT)	DBPORT="-TB_DEBUGPORT $2" ;shift;shift
				;;
		-TB_DEBUGHOST)  DBHOST="-TB_DEBUGHOST $2" ;shift;shift
				;;
		-script)	SCRIPT=$2 ;shift;shift
				;;
		-program)	PROGRAM=$2 ;shift;shift
				;;	
		-details)	DETAILS=$2 ;shift; shift
				;;
		-trace-calls)	TRACE="$TRACE -trace-calls" ;shift
				;;
		-arg)		ARGS="$ARGS $2" ;shift;shift
				;;
		-script-args)	shift; SCRIPTARGS="-script-args $@" ;shift
				;;
		-*)		$echo "unknown option: $1"
				$echo "$usage" >&2
				exit 1
				;;
		*) break
	esac
done

#echo "executing: $PROGRAM $ARGS $SCRIPT $NAME $HOST $PORT $TID $VERBOSE $DBPORT $DBHOST $TRACE -details $DETAILS $SCRIPTARGS"
$PROGRAM $ARGS $SCRIPT $NAME $HOST $PORT $TID $VERBOSE $DBPORT $DBHOST $TRACE -details "$DETAILS" $SCRIPTARGS 
