typedef struct _SDFCHARLIST *SDFCHARLIST;

ATbool SDFisValidCHARLIST(SDFCHARLIST arg);
ATbool SDFisCHARLISTString(SDFCHARLIST arg);
char*  SDFgetCHARLISTString(SDFCHARLIST arg);
SDFCHARLIST  SDFsetCHARLISTString(SDFCHARLIST arg, char *str);
ATerm  SDFCHARLISTToTerm(SDFCHARLIST arg);
SDFCHARLIST SDFCHARLISTFromTerm(ATerm trm);
SDFCHARLIST SDFmakeCHARLISTString(char *str);
