/**
 * This file is generated by tifstoc. Do not edit!
 * Generated from tifs for tool 'addapisyntax' (prefix='')
 * Implementation generated at Wed Oct 16 11:26:02 2002
 */

#include "addapisyntax.tif.h"

#define NR_SIG_ENTRIES	2

static char *signature[NR_SIG_ENTRIES] = {
  "rec-eval(<addapisyntax>,add-api-syntax(<term>))",
  "rec-terminate(<addapisyntax>,<term>)",
};

/* Event handler for tool 'addapisyntax' */
ATerm addapisyntax_handler(int conn, ATerm term)
{
  ATerm in, out;
  /* We need some temporary variables during matching */
  ATerm t0;

  if(ATmatch(term, "rec-eval(add-api-syntax(<term>))", &t0)) {
    return add_api_syntax(conn, t0);
  }
  if(ATmatch(term, "rec-terminate(<term>)", &t0)) {
    rec_terminate(conn, t0);
    return NULL;
  }
  if(ATmatch(term, "rec-do(signature(<term>,<term>))", &in, &out)) {
    ATerm result = addapisyntax_checker(conn, in);
    if(!ATmatch(result, "[]"))
      ATfprintf(stderr, "warning: not in input signature:\n\t%\n\tl\n", result);
    return NULL;
  }

  ATerror("tool addapisyntax cannot handle term %t", term);
  return NULL; /* Silence the compiler */
}

/* Check the signature of the tool 'addapisyntax' */
ATerm addapisyntax_checker(int conn, ATerm siglist)
{
  return ATBcheckSignature(siglist, signature, NR_SIG_ENTRIES);
}

