/**
 * This file is generated by tifstoc. Do not edit!
 * Generated from tifs for tool 'addeqssyntax' (prefix='')
 */

#ifndef _ADDEQSSYNTAX_H
#define _ADDEQSSYNTAX_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
void rec_terminate(int conn, ATerm);
ATerm add_eqs_syntax(int conn, const char *, ATerm);
extern ATerm addeqssyntax_handler(int conn, ATerm term);
extern ATerm addeqssyntax_checker(int conn, ATerm sigs);

#endif
