#! /bin/sh

# $Id$

Revision='$Revision$'

aterm=/opt/asfsdf-meta-1.5.3
pt_support=/opt/asfsdf-meta-1.5.3
sdf_support=/opt/asfsdf-meta-1.5.3
error_support=/opt/asfsdf-meta-1.5.3
graph_support=/opt/asfsdf-meta-1.5.3
sglr=/opt/asfsdf-meta-1.5.3
pandora=/opt/asfsdf-meta-1.5.3
pgen=/opt/asfsdf-meta-1.5.3
toolbus=/opt/asfsdf-meta-1.5.3
tide=/opt/asfsdf-meta-1.5.3
tide_support=/opt/asfsdf-meta-1.5.3
prefix=/opt/asfsdf-meta-1.5.3
editor=gnu-emacs
myversion=1.5.1

PATH="/home/poet/afstuderen/meta-toolimitator/:${prefix}/bin:${aterm}/bin:${pt_support}/bin:${sglr}/bin:${pgen}/bin:\
${error_support}/bin:${graph_support}/bin:${toolbus}/bin:\
${sdf_support}/bin:${pandora}/bin:${tide}/bin:${PATH}";
export PATH

CLASSPATH=/home/poet/afstuderen/meta-toolimitator/:`/opt/asfsdf-meta-1.5.3/bin/aterm-java-config`:/opt/asfsdf-meta-1.5.3/classes:`/opt/asfsdf-meta-1.5.3/bin/error-support-config`:/opt/asfsdf-meta-1.5.3/share/tide/tide.jar:${CLASSPATH}
export CLASSPATH



LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${prefix}/lib
export LD_LIBRARY_PATH
###
#  Handle the command line, &c.
###

myname=`basename $0`
verbose=0
xargs=""

# The argument vector: list of option letters, colons denote option
# arguments.  See Usage function, immediately below, for option
# explanation.
myarguments="C:I:de:hi:m:o:p:qr:sS:t:T:vV"

# Usage: displays helpful usage information
Usage() {
cat << E_O_USAGE >&2
Usage: $myname [options]
Options:
    -C file         specifies the configuration file to be processed
    -I dir          location of extra toolbus scripts
    -d              run in debug mode (with viewer)
    -e <editor>     select one of gnu-emacs, or gvim
    -h              display help information (usage)
    -i <file>       input file works only for the term-editor
    -m modulename   specifies the name of the top module to start with
    -o <file>       output file works only when dumping parse table or equations
    -p <path>       add <path> to PATH of Meta-Environment
    -q		    enable Meta-Environment query support
    -r <file>       uses given file as term-store
    -s              save intermediate files to disk
    -S              execute the given tb-script
    -t <int>        MetaEnvironment will abort after <int> seconds
    -T <port>       specifies TB_PORT for toolbus
    -v              run verbose mode (with logger)
    -V              reveal program version (i.e. $myversion)
E_O_USAGE
}

Version() {
    echo "$myname v$myversion" >&2
}

# getopt handles command line...
args=`getopt $myarguments $* 2> /dev/null`
if test $? != 0
then
        Usage
        exit 2
fi
set -- $args

# Argument interpretation...

configfile="meta.conf"
modulename=""
extra_scripts="-I${prefix}/share/meta"
meta_script=${prefix}/share/meta/meta-playback.tb
time_out_def=""
query_def=""
saving="false"
outputfilename=""
inputfilename=""
termstorename=""

while [ $#  -gt 0 ]
do
    case "$1"
    in
        -C)
                shift
                configfile=$1
                ;;    
        -d)
		xargs="${xargs} -viewer" 
		;;
	-e)
		shift
		editor=$1
		;;
        -h)
		Usage ; exit 0 
		;;
	-i)     
		shift
	        inputfilename=$1
		;;
        -I)     
		shift
	        extra_scripts="${extra_scripts} -I$1"
		;;
	-m)
		shift
		modulename=$1
		;;
	-o)     
		shift
	        outputfilename=$1
		;;
	-p)    
	        shift;
	        PATH="$1:${PATH}"
		export PATH
		;;
	-q)
		query_def="-DQUERY -I`meta-query-config`/share/meta-query"
		;;
	-r)     
		shift
	        termstorename=$1
		;;
	-s)     
		saving="true"
		;;
	-S)     
		shift
		meta_script="$1"
		;;
	-t)     
	        shift
		time_out_def="-DTIMEOUT=$1"
		;;
        -T)
		shift; 
		xargs="${xargs} -TB_PORT $1" 
		;;
        -v)
		xargs="${xargs} -logger"
		verbose=1 
		;;
	-V)
		Version ; exit 0 
		;;
	--)
		;;
	*)
		;;
    esac
    shift
done

###
#  Get to the real work now...
###
toolbusdefs="-DEDITOR=\\\"${editor}\\\" -DSAVING=\\\"${saving}\\\" -DINFILENAME=\\\"${inputfilename}\\\" -DOUTFILENAME=\\\"${outputfilename}\\\" -DMODULENAME=\\\"${modulename}\\\" -DTERMSTORENAME=\\\"${termstorename}\\\" -DCONFIG_FILE=\\\"${configfile}\\\" ${time_out_def} ${query_def}"

if [ $verbose -gt 0 ] ; then
   set -x
fi

toolbus -fixed-seed 1 -logger $xargs ${toolbusdefs} \
   -I${toolbus}/share/toolbus \
   -I${prefix}/share/meta \
   -I${aterm}/share \
   -I${error_support}/share/error-support \
   -I${pt_support}/share/pt-support \
   -I${sdf_support}/share/sdf-support \
   -I${graph_support}/share/graph-support \
   -I${sglr}/share/sglr \
   -I${tide}/share/tide \
   -I${tide_support}/share/tide-support \
   -I${pandora}/share/pandora \
   -I${pgen}/share/pgen \
   ${extra_scripts} \
   ${meta_script} \
   -fixed-seed 1
