#! /bin/sh -m
#
#

DEFS="-Dtide.enabled=true -Dcom.apple.macos.useScreenMenuBar=true -Dcom.apple.mrj.application.apple.menu.about.name=Meta-Environment" 


  CLASSPATH="/opt/asfsdf-meta-1.5.3/share/meta/meta-studio.jar:/opt/asfsdf-meta-1.5.3/share/meta-test/meta-logger.jar:/opt/asfsdf-meta-1.5.3/share/aterm-1.6.2.jar:/opt/asfsdf-meta-1.5.3/share/shared-objects-1.4.2.jar:/opt/asfsdf-meta-1.5.3/share/jjtraveler-0.4.5.jar:/opt/asfsdf-meta-1.5.3/classes:/opt/asfsdf-meta-1.5.3/share/error-support/errorapi-1.0.1.jar:/opt/asfsdf-meta-1.5.3/share/error-support/locationapi-1.0.1.jar:/opt/asfsdf-meta-1.5.3/share/tide/tide.jar:$CLASSPATH"
  export CLASSPATH
  /usr/java/j2sdk1.4.2_05/bin/java -Xmx256m metalogger.MetaLogger $@

