#! /bin/sh
#
# $Id$
#
# For each individual package in the Asf+Sdf Meta-Environment
# distribution that is controlled by automake, run "reconf" for
# that package prior to "configure".

# Tell aclocal where it can find libtool.m4
LIBTOOL=`which libtool`
LIBTOOL=`dirname ${LIBTOOL}`
LIBTOOL=`dirname ${LIBTOOL}`
LIBTOOL_INCLUDE=${LIBTOOL}/share/aclocal

aclocal -I ${LIBTOOL_INCLUDE} -I ./config
autoconf
autoheader
automake -a
