#! /bin/perl
# $Id$

$instring = 0;

while (<STDIN>) {
    if ((/\"/ && !(/\".*\"/)) && $instring) {
	chop;
	print $_; 
	$instring = 0;
    } elsif ((/\"/ && !(/\".*\"/)) && !$instring) {
	chop;
	print $_;
	$instring = 1;
    } elsif ($instring) {
	chop;
	print $_;
    } elsif (!$instring) {
	s/subgraph broadcast \{/subgraph broadcast \{edge \[color = grey\];/;
	s/subgraph creation \{/subgraph broadcast \{edge \[color = green\];/;
	s/subgraph events \{/subgraph broadcast \{edge \[color = yellow\];/;
	s/subgraph evals \{/subgraph broadcast \{edge \[color = brown\];/;
	s/subgraph dos \{/subgraph broadcast \{edge \[color = orange\];/;
	s/subgraph values \{/subgraph broadcast \{edge \[color = blue\];/;
	print $_;
    }
} 

