/**
 * This file is generated by /ufs/jurgenv/glt/bin/tifstoc. Do not edit!
 * Generated from tifs for tool 'asfoperations' (prefix='')
 * Headerfile generated at Wed Oct 15 16:29:13 2003
 */

#ifndef _ASFOPERATIONS_H
#define _ASFOPERATIONS_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
ATerm extract_equations(int conn, ATerm);
ATerm extract_tests(int conn, ATerm);
void rec_terminate(int conn, ATerm);
extern ATerm asfoperations_handler(int conn, ATerm term);
extern ATerm asfoperations_checker(int conn, ATerm sigs);

#endif
