/**
 * This file is generated by tifstoc. Do not edit!
 * Generated from tifs for tool 'dot-adapter' (prefix='')
 * Headerfile generated at Fri Mar 28 16:52:13 2003
 */

#ifndef _DOT_ADAPTER_H
#define _DOT_ADAPTER_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
ATerm layout_graph(int conn, ATerm);
void rec_terminate(int conn, ATerm);
extern ATerm dot_adapter_handler(int conn, ATerm term);
extern ATerm dot_adapter_checker(int conn, ATerm sigs);

#endif
