#! /bin/sh

set -e
datadir=/home/paulk/research/relation-calculus/tmp/share/relation-calculus
bindir=/home/paulk/research/relation-calculus/tmp/bin
TABLE=${datadir}/Rstore.trm.tbl
RSTORE=${bindir}/Rstore
RESULT=result.rstore.pt

echo -n "creating empty ${RESULT} .."
echo "rstore()" | sglr -p ${TABLE} -o ${RESULT}
echo " done."

for f in $*; do
  echo -n "merging $f into ${RESULT} .."
  $RSTORE -f merge-rstores -r RSTORE -i $f -i ${RESULT} -o ${RESULT}
  echo " done."
done

ls -l ${RESULT}
