#! /bin/sh

set -e

TABLE=/ufs/jong/Research/RPA/RscriptCalculator.trm.tbl
RESULT=result.rstore

echo -n "creating empty ${RESULT} .."
echo "rstore()" | sglr -p ${TABLE} -o ${RESULT}
echo " done."

for f in $*; do
  echo -n "merging $f into ${RESULT} .."
  Rstore -f merge-rstores -r RSTORE -i $f -i ${RESULT} -o ${RESULT}
  echo " done."
done

ls -l ${RESULT}
