/*

    PGEN - the SDF2 parse table generator.
    Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam, 
    The Netherlands. 

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA

*/
/* This C code is generated by the AsfSdfCompiler version 1.0 */

#include  "asc-support.h"
static Symbol lf_AUX_Symbols_Projection5_1sym;
static ATerm lf_AUX_Symbols_Projection5_1 (ATerm arg1, ATerm arg2);
static Symbol ef2sym;
static funcptr ef2;
static Symbol ef3sym;
static funcptr ef3;
static Symbol ef1sym;
static funcptr ef1;
static Symbol lf2sym;
static ATerm lf2 (ATerm arg1);
void
register_AUX_Symbols_Projection5 ()
{
  lf_AUX_Symbols_Projection5_1sym =
    ATmakeSymbol
    ("prod(id(\"Symbols-Projection\"),w(\"\"),[sort(\"Symbol\"),w(\"\"),ql(\"nm-(-\"),w(\"\"),sort(\"Symbols\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)",
     2, ATtrue);
  ATprotectSymbol (lf_AUX_Symbols_Projection5_1sym);
  lf2sym = ATmakeSymbol ("listtype(sort(\"Symbol\"))", 1, ATtrue);
  ATprotectSymbol (lf2sym);
  register_prod (ATparse
		 ("prod(id(\"Symbols-Projection\"),w(\"\"),[sort(\"Symbol\"),w(\"\"),ql(\"nm-(-\"),w(\"\"),sort(\"Symbols\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)"),
		 lf_AUX_Symbols_Projection5_1,
		 lf_AUX_Symbols_Projection5_1sym);
  register_prod (ATparse ("listtype(sort(\"Symbol\"))"), lf2, lf2sym);
}

void
resolve_AUX_Symbols_Projection5 ()
{
  ef1 =
    lookup_func (ATreadFromString
		 ("prod(id(\"Symbols\"),w(\"\"),[iter(sort(\"Symbol\"),w(\"\"),l(\"*\"))],w(\"\"),l(\"->\"),w(\"\"),sort(\"Symbols\"),w(\"\"),no-attrs)"));
  ef1sym =
    lookup_sym (ATreadFromString
		("prod(id(\"Symbols\"),w(\"\"),[iter(sort(\"Symbol\"),w(\"\"),l(\"*\"))],w(\"\"),l(\"->\"),w(\"\"),sort(\"Symbols\"),w(\"\"),no-attrs)"));
  ef2 =
    lookup_func (ATreadFromString
		 ("prod(id(\"Booleans\"),w(\"\"),[ql(\"false\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)"));
  ef2sym =
    lookup_sym (ATreadFromString
		("prod(id(\"Booleans\"),w(\"\"),[ql(\"false\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)"));
  ef3 =
    lookup_func (ATreadFromString
		 ("prod(id(\"Booleans\"),w(\"\"),[ql(\"true\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)"));
  ef3sym =
    lookup_sym (ATreadFromString
		("prod(id(\"Booleans\"),w(\"\"),[ql(\"true\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)"));
}
static ATerm constant0 = NULL;
static ATerm constant1 = NULL;
void
init_AUX_Symbols_Projection5 ()
{
  ATprotect (&constant0);
  ATprotect (&constant1);
}

ATerm
lf_AUX_Symbols_Projection5_1 (ATerm arg0, ATerm arg1)
{ {
  ATerm tmp[2];
  FUNC_ENTRY (lf_AUX_Symbols_Projection5_1sym,
		ATmakeAppl (lf_AUX_Symbols_Projection5_1sym, arg0, arg1));
   {
    ATerm ltmp[2];
      ltmp[0] = arg0;
    if (check_sym (arg1, ef1sym)) { {
	ATerm atmp10 = arg_0 (arg1);
	if (check_sym (atmp10, lf2sym)) { {
	  ATerm atmp100 = arg_0 (atmp10);
    lbl_lf_AUX_Symbols_Projection5_1:
      ltmp[1] = atmp100;
	  if (not_empty_list (atmp100)) {
	      (tmp[0] = list_head (atmp100));
	      {
		(tmp[1] = list_tail (atmp100));
		if (!term_equal (ltmp[0], tmp[0])) {
		    (atmp100 = make_list (tmp[1]));
		    goto lbl_lf_AUX_Symbols_Projection5_1;
		  }
		else {
		    FUNC_EXIT_CONST (constant0, (*ef3) ());
		  }
	      }
	    }
	  else {
	      FUNC_EXIT_CONST (constant1, (*ef2) ());
	    }
	}
	}
	 }
	}
      FUNC_EXIT (make_nf2
		 (lf_AUX_Symbols_Projection5_1sym, ltmp[0], ltmp[1]));
    }
  }
}
ATerm
lf2 (ATerm arg0)
{
  CONS_ENTRY (lf2sym, ATmakeAppl (lf2sym, arg0));
  CONS_EXIT (make_nf1 (lf2sym, arg0));
}
