/**
 * This file is generated by /ufs/markvdb/Research/bin/tifstoc. Do not edit!
 * Generated from tifs for tool 'addPosInfo' (prefix='')
 * Headerfile generated at Fri Jan 31 11:25:29 2003
 */

#ifndef _ADDPOSINFO_H
#define _ADDPOSINFO_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
ATerm addPosInfo(int conn, char *, ATerm);
void rec_terminate(int conn, ATerm);
extern ATerm addPosInfo_handler(int conn, ATerm term);
extern ATerm addPosInfo_checker(int conn, ATerm sigs);

#endif
