/**
 * This file is generated by /users/protheo/vinju/software/bin/tifstoc. Do not edit!
 * Generated from tifs for tool 'addPosInfo' (prefix='')
 * Headerfile generated at Tue Oct 29 15:05:28 2002
 */

#ifndef _ADDPOSINFO_H
#define _ADDPOSINFO_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
ATerm addPosInfo(int conn, char *, ATerm);
void rec_terminate(int conn, ATerm);
extern ATerm addPosInfo_handler(int conn, ATerm term);
extern ATerm addPosInfo_checker(int conn, ATerm sigs);

#endif
