/* This C code is generated by the AsfSdfCompiler version 1.0 */

#include  "asc-support.h"
static Symbol lf_AUX_Traversals3_1sym ;
static ATerm lf_AUX_Traversals3_1 ( ATerm arg1 ) ;
static Symbol ef1sym ;
static funcptr ef1 ;
void register_AUX_Traversals3 ( ) {
lf_AUX_Traversals3_1sym = ATmakeSymbol ( "prod(id(\"Traversals\"),w(\"\"),[ql(\"GenerateTraversals\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Definition\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Definition\"),w(\"\"),no-attrs)"
 , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Traversals3_1sym ) ;
register_prod ( ATparse ( "prod(id(\"Traversals\"),w(\"\"),[ql(\"GenerateTraversals\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Definition\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Definition\"),w(\"\"),no-attrs)" ) , lf_AUX_Traversals3_1 , lf_AUX_Traversals3_1sym ) ;
}
void resolve_AUX_Traversals3 ( ) {
ef1 = lookup_func ( ATreadFromString ( "prod(id(\"Traversals\"),w(\"\"),[ql(\"generate_definition\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Definition\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"Definition\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Definition\"),w(\"\"),no-attrs)" ) ) ;
ef1sym = lookup_sym ( ATreadFromString ( "prod(id(\"Traversals\"),w(\"\"),[ql(\"generate_definition\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Definition\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"Definition\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Definition\"),w(\"\"),no-attrs)" ) ) ;
}
void init_AUX_Traversals3 ( ) {
}
ATerm lf_AUX_Traversals3_1 ( ATerm arg0 ) {
FUNC_ENTRY ( lf_AUX_Traversals3_1sym , ATmakeAppl ( lf_AUX_Traversals3_1sym , arg0 ) ) ;
FUNC_EXIT ( ( * ef1 ) ( arg0 , arg0 ) ) ;
FUNC_EXIT ( make_nf1 ( lf_AUX_Traversals3_1sym , arg0 ) ) ;
}

