/* This C code is generated by the AsfSdfCompiler version 1.0 */

#include  "asc-support.h"
static Symbol lf_AUX_Traversals_Add2_1sym ;
static ATerm lf_AUX_Traversals_Add2_1 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol ef1sym ;
static funcptr ef1 ;
void register_AUX_Traversals_Add2 ( ) {
lf_AUX_Traversals_Add2_1sym = ATmakeSymbol ( "prod(id(\"Traversals-Add\"),w(\"\"),[ql(\"add_productions\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Module\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"Productions\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Module\"),w(\"\"),no-attrs)"
 , 2 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Traversals_Add2_1sym ) ;
register_prod ( ATparse ( "prod(id(\"Traversals-Add\"),w(\"\"),[ql(\"add_productions\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Module\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"Productions\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Module\"),w(\"\"),no-attrs)" ) , lf_AUX_Traversals_Add2_1 , lf_AUX_Traversals_Add2_1sym ) ;
}
void resolve_AUX_Traversals_Add2 ( ) {
ef1 = lookup_func ( ATreadFromString ( "prod(id(\"Traversals-Add\"),w(\"\"),[ql(\"add_to_module\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Module\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"Productions\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Module\"),w(\"\"),no-attrs)" ) ) ;
ef1sym = lookup_sym ( ATreadFromString ( "prod(id(\"Traversals-Add\"),w(\"\"),[ql(\"add_to_module\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Module\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"Productions\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Module\"),w(\"\"),no-attrs)" ) ) ;
}
void init_AUX_Traversals_Add2 ( ) {
}
ATerm lf_AUX_Traversals_Add2_1 ( ATerm arg0 , ATerm arg1 ) {
FUNC_ENTRY ( lf_AUX_Traversals_Add2_1sym , ATmakeAppl ( lf_AUX_Traversals_Add2_1sym , arg0 , arg1 ) ) ;
FUNC_EXIT ( ( * ef1 ) ( arg0 , arg1 ) ) ;
FUNC_EXIT ( make_nf2 ( lf_AUX_Traversals_Add2_1sym , arg0 , arg1 ) ) ;
}

