=head1 NAME

SGLR - the Scannerless Generalized LR parser

=head1 SYNOPSIS

B<sglr> -B<p> file [-B<2?AbcdhlmnstvV>] [-B<f>[adeirp]] [-B<i> I<file>] [-B<o> I<file>] [-B<s> I<sort>]

=head1 DESCRIPTION

The B<sglr> parser uses a specified I<parse table> to parse an I<input file>.
After a successful parse, the resulting parse forest is written to an
I<output file>.

A number of options can be supplied; these are as follows:

=over 4

=item -B<2>

Generate AsFix2 output format.  

=item -B<A>

Ambiguities are treated as errors.

=item -B<b>, -B<t>

Choose between binary (B<b>) and plaintext (B<t>) output formats.  Default
is binary output.

=item -B<c>

Toggles cycle detection (on by default).

=item -B<d>

Toggles debug mode.  In debug mode, a full trace for the entire parse
is maintained in the F<.sglr-log>.  Be alert: such files tend to become
rather big.

=item -B<f>

The parser applies a number of filters to ambiguous trees after the parsing
process has finished. Just supplying the -B<f> option toggles the application
of all filters. Specific filters can be toggled by using -B<f> with an
additional letter:

 a : associativity        
 d : direct eagerness    
 e : eagerness          
 i : injection count   
 p : priority         
 r : reject          

 e.g., "sglr -fi" will toggle the injection count filter.

These specific toggles are supposed to be used for debugging purposes only.
So, do not use these options to tweak your language implementations! It is
highly probable that there will be no backward compatibility for them in 
future versions.

=item -B<i> I<file>

Read input from F<file>; by default, input is read from stdin.

=item -B<?>, -B<h>

Prints concise usage information (reflecting current setup).

=item -B<l>

Toggles statistics mode (off by default).  Produces some run-time
statistics in F<sglr-stats.txt>, including time and - on platforms
on which these can be obtained - memory usage data.

=item -B<m>

Generate AsFix2ME output format.  This is the default format.

=item -B<n>

Toggles the contruction of the parse tree (on by default).  

=item -B<o> I<file>

Write output to F<file>; by default, output is written to stdout.
Note that strange things are bound to happen when writing binary
output to a tty.

=item -B<s> I<sort>

Only parse trees that have I<sort> at their root are accepted.

=item -B<v>

Toggles verbose operation.

=item -B<V>

Displays the program's version number.

=back

=head1 USAGE

To parse, the B<sglr> parser requires a parse table.  Instantiated with
that parse table, it has become a parser for the language defined by
the grammar corresponding to the specified parse table.

=head1 EXAMPLES

    $ sglr -h
    Usage:
      sglr    -p file [-2?AbcdhlmntvV] [-f[adeirp]] [-i file] [-o file] \
              [-s sort]
    [. . .]
    $ sglr -vp Test.tbl -i MyCode.cod -o Output.File -l
    sglr: logging to sglr-stats.txt
    sglr: opening parse table Test.tbl
    sglr: parsing file MyCode.cod (1 tokens)
    sglr: writing parse result to Output.File
    sglr: Test.tbl parsed MyCode.cod as sort S, exactly 0 ambiguities

=head1 EXIT STATUS

Returns an error on unsuccesful parses.

=head1 SEE ALSO

L<sdf2table>

=head1 REFERENCES

=for docbook
	GraphViz: <http://www.research.att.com/sw/tools/graphviz/>

=for html
	<A HREF="http://www.research.att.com/sw/tools/graphviz/">GraphViz</A>

=for mf
	GraphViz: <http://www.research.att.com/sw/tools/graphviz/>

=for man
	GraphViz: <http://www.research.att.com/sw/tools/graphviz/>

=for text
	GraphViz: <http://www.research.att.com/sw/tools/graphviz/>

=head1 NOTES

In a different context altogether, B<sglr> runs as a C<ToolBus> client.

=head1 MAINTAINER

Mark van den Brand <S<Mark.van.den.Brand@cwi.nl>>
