#! /bin/sh

set -e

TABLE=/ufs/jong/Research/RPA/RscriptCalculator.trm.tbl
RESULT=result.rstore

echo -n "creating empty ${RESULT} .."
echo "[]" | sglr -p ${TABLE} -o ${RESULT}
echo " done."

for f in $*; do
  echo -n "merging $f into ${RESULT} .."
  MergeRstores -f merge -i ${RESULT} -i $f -o ${RESULT}
  echo " done."
done

ls -l ${RESULT}
