#!/bin/sh
#
#    ToolBus -- The ToolBus Application Architecture
#    Copyright (C) 1998-2000  Stichting Mathematisch Centrum, Amsterdam, 
#                             The  Netherlands.
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
PROGRAM=tbswipl
NAME="assert(tb_tool(unknown)),"
TBHOST="assert(tb_host($HOST)),"
PORT="assert(tb_port(8998)),"
TID="assert(tb_tid(-1)),"


TRACE="assert(tb_trace(no))"
VERBOSE="assert(tb_verbose(no)),"

usage="$0 -TB_TOOL_NAME <name> -TB_HOST <host> -TB_PORT <port> -TB_TOOL_ID <tid> -TB_VERBOSE -script <script> -program <prog>"

while :
do
	case "$1" in
		-TB_TOOL_NAME)	NAME="assert(tb_tool($2))," ;shift;shift
				;;
		-TB_HOST)	TBHOST="assert(tb_host('$2'))," ;shift;shift
				;;
		-TB_PORT)	PORT="assert(tb_port($2))," ;shift;shift
				;;
		-TB_TOOL_ID)	TID="assert(tb_tid($2))," ;shift;shift
				;;
		-TB_VERBOSE)	VERBOSE="assert(tb_verbose(yes))," ;shift
				;;
		-TB_DEBUGPORT)	DBPORT="-TB_DEBUGPORT $2" ;shift;shift
				;;
		-TB_DEBUGHOST)  DBHOST="-TB_DEBUGHOST $2" ;shift;shift
				;;
		-program)	PROGRAM=$2 ;shift;shift
				;;	
		-goal)		GOAL="-t $2"; shift; shift
				;;
		-trace-calls)	TRACE="assert(tb_trace(yes))" ;shift
				;;
		-arg)		ARGS="$ARGS $2" ;shift;shift
				;;
		-details)	DETAILS=$2; shift;shift
				;;
		-script-args)	shift; SCRIPTARGS="assert(tb_args('$@'))" ;shift;shift;shift;shift;shift;shift;shift;shift;shift;shift;shift;shift;shift
				;;
		-*)		$echo "unknown option: $1"
				$echo "$usage" >&2
				exit 1
				;;
		*) break
	esac
done

ASRT="assert(port($PORT))"

#echo "executing: $PROGRAM $ARGS -tty $GOAL -g $NAME$TBHOST$PORT$TID$VERBOSE$TRACE"
$PROGRAM $ARGS -tty $GOAL -g "$NAME$TBHOST$PORT$TID$VERBOSE$TRACE" < /dev/null
