#!/bin/sh

#
# To add a term to the test:
#         1. Provide the test term as <name>.test.asfix1
#         2. Provide a reference reduced term as <name>.reference.asfix1
#         3. Add a call to test_traversals
#

tests=0
failed=0

test_traversals() {
  tests=`expr $tests + 1`
  input=$1.test.asfix1
  rm -f $input.check.asfix1
  ../src/traversals -i $input -o $input.check.asfix1
  if cmp -s $input.reference.asfix1 $input.check.asfix1 ; then 
    failed=`expr $failed + 1`
    return 1;
  else
    printf . 
  fi

  rm -f $input.check.asfix1
}

# calls to test_traversals for each test
test_traversals Pico-Syntax-Traversals


# end of calls to test_traversal

printf "\n"

if [ $failed != 0 ]; then
   echo "FAILED:" $failed "out of" $tests "tests"
   exit 1
else
   echo "All" $tests "tests succeeded"
fi


