/**
 * This file is generated by ../../aterm/tifstoc. Do not edit!
 * Generated from tifs for tool 'dot-adapter' (prefix='')
 * Implementation generated at Fri Feb  7 09:15:45 2003
 */

#include "dot-adapter.tif.h"

#define NR_SIG_ENTRIES	2

static char *signature[NR_SIG_ENTRIES] = {
  "rec-eval(<dot-adapter>,layout-graph(<term>))",
  "rec-terminate(<dot-adapter>,<term>)",
};

/* Event handler for tool 'dot-adapter' */
ATerm dot_adapter_handler(int conn, ATerm term)
{
  ATerm in, out;
  /* We need some temporary variables during matching */
  ATerm t0;

  if(ATmatch(term, "rec-eval(layout-graph(<term>))", &t0)) {
    return layout_graph(conn, t0);
  }
  if(ATmatch(term, "rec-terminate(<term>)", &t0)) {
    rec_terminate(conn, t0);
    return NULL;
  }
  if(ATmatch(term, "rec-do(signature(<term>,<term>))", &in, &out)) {
    ATerm result = dot_adapter_checker(conn, in);
    if(!ATmatch(result, "[]"))
      ATfprintf(stderr, "warning: not in input signature:\n\t%\n\tl\n", result);
    return NULL;
  }

  ATerror("tool dot-adapter cannot handle term %t", term);
  return NULL; /* Silence the compiler */
}

/* Check the signature of the tool 'dot-adapter' */
ATerm dot_adapter_checker(int conn, ATerm siglist)
{
  return ATBcheckSignature(siglist, signature, NR_SIG_ENTRIES);
}

