/* This C code is generated by the asf compiler version 2.5 */

#include  "asc-support-me.h"
static Symbol lf_1sym ;
static ATerm lf_1 ( ) ;
static Symbol lf_2sym ;
static ATerm lf_2 ( ATerm arg1 ) ;
static Symbol lf_3sym ;
static ATerm lf_3 ( ATerm arg1 ) ;
static Symbol lf_4sym ;
static ATerm lf_4 ( ) ;
static Symbol lf_5sym ;
static ATerm lf_5 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol lf_6sym ;
static ATerm lf_6 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol lf_list_7sym ;
static ATerm lf_list_7 ( ATerm arg1 ) ;
static Symbol lf_8sym ;
static ATerm lf_8 ( ATerm arg1 ) ;
static Symbol lf_9sym ;
static ATerm lf_9 ( ATerm arg1 , ATerm arg2 , ATerm arg3 , ATerm arg4 ) ;
static Symbol lf_accu_td_10sym ;
static ATerm lf_accu_td_10 ( ATerm arg1 , ATerm arg2 , ATerm arg3 ) ;
static Symbol lf_11sym ;
static ATerm lf_11 ( ATerm arg1 , ATerm arg2 , ATerm arg3 ) ;
static Symbol lf_12sym ;
static ATerm lf_12 ( ATerm arg1 , ATerm arg2 ) ;
void register_FindSortDefinition ( ) {
lf_1sym = ATmakeSymbol ( "prod([lit(\"true\")],cf(sort(\"BoolCon\")),attrs([term(constructor)]))"
 , 0 , ATtrue ) ;
ATprotectSymbol ( lf_1sym ) ;
lf_2sym = ATmakeSymbol ( "prod([cf(sort(\"BoolCon\"))],cf(sort(\"Boolean\")),no-attrs)" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_2sym ) ;
lf_3sym = ATmakeSymbol ( "prod([lit(\"not\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),cf(sort(\"Boolean\")),cf(opt(layout)),lit(\")\")],cf(sort(\"Boolean\")),no-attrs)" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_3sym ) ;
lf_4sym = ATmakeSymbol ( "prod([lit(\"false\")],cf(sort(\"BoolCon\")),attrs([term(constructor)]))" , 0 , ATtrue ) ;
ATprotectSymbol ( lf_4sym ) ;
lf_5sym = ATmakeSymbol ( "prod([cf(sort(\"Boolean\")),cf(opt(layout)),lit(\"&\"),cf(opt(layout)),cf(sort(\"Boolean\"))],cf(sort(\"Boolean\")),attrs([assoc(left)]))" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_5sym ) ;
lf_6sym = ATmakeSymbol ( "prod([cf(sort(\"Boolean\")),cf(opt(layout)),lit(\"|\"),cf(opt(layout)),cf(sort(\"Boolean\"))],cf(sort(\"Boolean\")),attrs([assoc(left)]))" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_6sym ) ;
lf_list_7sym = ATmakeSymbol ( "list(cf(iter-star-sep(sort(\"Symbol\"),lit(\",\"))))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_list_7sym ) ;
lf_8sym = ATmakeSymbol ( "prod([cf(sort(\"Sort\"))],cf(sort(\"Symbol\")),no-attrs)" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_8sym ) ;
lf_9sym = ATmakeSymbol ( "prod([cf(sort(\"Literal\")),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),cf(iter-star-sep(sort(\"Symbol\"),lit(\",\"))),cf(opt(layout)),lit(\")\"),cf(opt(layout)),lit(\"->\"),cf(opt(layout)),cf(sort(\"Symbol\")),cf(opt(layout)),cf(sort(\"Attributes\"))],cf(sort(\"Production\")),attrs([avoid]))" , 4 , ATtrue ) ;
ATprotectSymbol ( lf_9sym ) ;
lf_accu_td_10sym = ATmakeSymbol ( "prod([lit(\"contains-sort-definition\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),sort(\"***TRAVERSED***\"),cf(opt(layout)),lit(\",\"),cf(opt(layout)),cf(sort(\"Boolean\")),cf(opt(layout)),lit(\",\"),cf(opt(layout)),cf(sort(\"Sort\")),cf(opt(layout)),lit(\")\")],cf(sort(\"Boolean\")),attrs([term(traversal(accu,break,top-down)),id(\"FindSortDefinition\")]))" , 3 , ATtrue ) ;
ATprotectSymbol ( lf_accu_td_10sym ) ;
lf_11sym = ATmakeSymbol ( "prod([cf(sort(\"Symbols\")),cf(opt(layout)),lit(\"->\"),cf(opt(layout)),cf(sort(\"Symbol\")),cf(opt(layout)),cf(sort(\"Attributes\"))],cf(sort(\"Production\")),no-attrs)" , 3 , ATtrue ) ;
ATprotectSymbol ( lf_11sym ) ;
lf_12sym = ATmakeSymbol ( "prod([lit(\"find-sort-definition\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),cf(sort(\"Module\")),cf(opt(layout)),lit(\",\"),cf(opt(layout)),cf(sort(\"Sort\")),cf(opt(layout)),lit(\")\")],cf(sort(\"Boolean\")),no-attrs)" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_12sym ) ;
register_prod ( ATparse ( "prod([lit(\"true\")],cf(sort(\"BoolCon\")),attrs([term(constructor)]))" ) , lf_1 , lf_1sym ) ;
register_prod ( ATparse ( "prod([cf(sort(\"BoolCon\"))],cf(sort(\"Boolean\")),no-attrs)" ) , lf_2 , lf_2sym ) ;
register_prod ( ATparse ( "prod([lit(\"not\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),cf(sort(\"Boolean\")),cf(opt(layout)),lit(\")\")],cf(sort(\"Boolean\")),no-attrs)" ) , lf_3 , lf_3sym ) ;
register_prod ( ATparse ( "prod([lit(\"false\")],cf(sort(\"BoolCon\")),attrs([term(constructor)]))" ) , lf_4 , lf_4sym ) ;
register_prod ( ATparse ( "prod([cf(sort(\"Boolean\")),cf(opt(layout)),lit(\"&\"),cf(opt(layout)),cf(sort(\"Boolean\"))],cf(sort(\"Boolean\")),attrs([assoc(left)]))" ) , lf_5 , lf_5sym ) ;
register_prod ( ATparse ( "prod([cf(sort(\"Boolean\")),cf(opt(layout)),lit(\"|\"),cf(opt(layout)),cf(sort(\"Boolean\"))],cf(sort(\"Boolean\")),attrs([assoc(left)]))" ) , lf_6 , lf_6sym ) ;
register_prod ( ATparse ( "list(cf(iter-star-sep(sort(\"Symbol\"),lit(\",\"))))" ) , lf_list_7 , lf_list_7sym ) ;
register_prod ( ATparse ( "prod([cf(sort(\"Sort\"))],cf(sort(\"Symbol\")),no-attrs)" ) , lf_8 , lf_8sym ) ;
register_prod ( ATparse ( "prod([cf(sort(\"Literal\")),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),cf(iter-star-sep(sort(\"Symbol\"),lit(\",\"))),cf(opt(layout)),lit(\")\"),cf(opt(layout)),lit(\"->\"),cf(opt(layout)),cf(sort(\"Symbol\")),cf(opt(layout)),cf(sort(\"Attributes\"))],cf(sort(\"Production\")),attrs([avoid]))" ) , lf_9 , lf_9sym ) ;
register_prod ( ATparse ( "prod([lit(\"contains-sort-definition\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),sort(\"***TRAVERSED***\"),cf(opt(layout)),lit(\",\"),cf(opt(layout)),cf(sort(\"Boolean\")),cf(opt(layout)),lit(\",\"),cf(opt(layout)),cf(sort(\"Sort\")),cf(opt(layout)),lit(\")\")],cf(sort(\"Boolean\")),attrs([term(traversal(accu,break,top-down)),id(\"FindSortDefinition\")]))" ) , lf_accu_td_10 , lf_accu_td_10sym ) ;
register_prod ( ATparse ( "prod([cf(sort(\"Symbols\")),cf(opt(layout)),lit(\"->\"),cf(opt(layout)),cf(sort(\"Symbol\")),cf(opt(layout)),cf(sort(\"Attributes\"))],cf(sort(\"Production\")),no-attrs)" ) , lf_11 , lf_11sym ) ;
register_prod ( ATparse ( "prod([lit(\"find-sort-definition\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),cf(sort(\"Module\")),cf(opt(layout)),lit(\",\"),cf(opt(layout)),cf(sort(\"Sort\")),cf(opt(layout)),lit(\")\")],cf(sort(\"Boolean\")),no-attrs)" ) , lf_12 , lf_12sym ) ;
}
void resolve_FindSortDefinition ( ) {
}
static ATerm constant0 = NULL ;
static ATerm constant1 = NULL ;
void init_FindSortDefinition ( ) {
ATprotect ( & constant0 ) ;
ATprotect ( & constant1 ) ;
}
ATerm lf_12 ( ATerm arg0 , ATerm arg1 ) {
FUNC_ENTRY ( lf_12sym , ATmakeAppl ( lf_12sym , arg0 , arg1 ) ) ;
FUNC_EXIT ( lf_accu_td_10 ( arg0 , make_nf1 ( lf_2sym , make_nf0 ( lf_4sym ) ) , arg1 ) ) ;
FUNC_EXIT ( make_nf2 ( lf_12sym , arg0 , arg1 ) ) ;
}
ATerm lf_accu_td_10 ( ATerm arg0 , ATerm arg1 , ATerm arg2 ) {
FUNC_ENTRY ( lf_accu_td_10sym , ATmakeAppl ( lf_accu_td_10sym , arg0 , arg1 , arg2 ) ) ;
if ( check_sym ( arg0 , lf_9sym ) ) {
{
ATerm atmp00 = arg_0 ( arg0 ) ;
{
ATerm atmp01 = arg_1 ( arg0 ) ;
if ( check_sym ( atmp01 , lf_list_7sym ) ) {
{
ATerm atmp010 = arg_0 ( atmp01 ) ;
{
ATerm atmp02 = arg_2 ( arg0 ) ;
if ( check_sym ( atmp02 , lf_8sym ) ) {
{
ATerm atmp020 = arg_0 ( atmp02 ) ;
{
ATerm atmp03 = arg_3 ( arg0 ) ;
if ( term_equal ( atmp020 , arg2 ) ) {
FUNC_EXIT_CONST ( constant0 , make_nf1 ( lf_2sym , make_nf0 ( lf_1sym ) ) ) ;
}
}
}
}
}
}
}
}
}
}
if ( check_sym ( arg0 , lf_11sym ) ) {
{
ATerm atmp00 = arg_0 ( arg0 ) ;
{
ATerm atmp01 = arg_1 ( arg0 ) ;
if ( check_sym ( atmp01 , lf_8sym ) ) {
{
ATerm atmp010 = arg_0 ( atmp01 ) ;
{
ATerm atmp02 = arg_2 ( arg0 ) ;
if ( term_equal ( atmp010 , arg2 ) ) {
FUNC_EXIT_CONST ( constant0 , make_nf1 ( lf_2sym , make_nf0 ( lf_1sym ) ) ) ;
}
}
}
}
}
}
}
FUNC_EXIT ( call_kids_accu ( lf_accu_td_10 , arg0 , arg1 , ATmakeList1 ( arg2 ) ) ) ;
}
ATerm lf_6 ( ATerm arg0 , ATerm arg1 ) {
FUNC_ENTRY ( lf_6sym , ATmakeAppl ( lf_6sym , arg0 , arg1 ) ) ;
if ( term_equal ( arg0 , ( constant1 ? constant1 : ( constant1 = make_nf1 ( lf_2sym , make_nf0 ( lf_4sym ) ) ) ) ) ) {
FUNC_EXIT ( arg1 ) ;
}
if ( term_equal ( arg0 , ( constant0 ? constant0 : ( constant0 = make_nf1 ( lf_2sym , make_nf0 ( lf_1sym ) ) ) ) ) ) {
FUNC_EXIT_CONST ( constant0 , make_nf1 ( lf_2sym , make_nf0 ( lf_1sym ) ) ) ;
}
FUNC_EXIT ( make_nf2 ( lf_6sym , arg0 , arg1 ) ) ;
}
ATerm lf_5 ( ATerm arg0 , ATerm arg1 ) {
FUNC_ENTRY ( lf_5sym , ATmakeAppl ( lf_5sym , arg0 , arg1 ) ) ;
if ( term_equal ( arg0 , ( constant1 ? constant1 : ( constant1 = make_nf1 ( lf_2sym , make_nf0 ( lf_4sym ) ) ) ) ) ) {
FUNC_EXIT_CONST ( constant1 , make_nf1 ( lf_2sym , make_nf0 ( lf_4sym ) ) ) ;
}
if ( term_equal ( arg0 , ( constant0 ? constant0 : ( constant0 = make_nf1 ( lf_2sym , make_nf0 ( lf_1sym ) ) ) ) ) ) {
FUNC_EXIT ( arg1 ) ;
}
FUNC_EXIT ( make_nf2 ( lf_5sym , arg0 , arg1 ) ) ;
}
ATerm lf_3 ( ATerm arg0 ) {
FUNC_ENTRY ( lf_3sym , ATmakeAppl ( lf_3sym , arg0 ) ) ;
if ( term_equal ( arg0 , ( constant0 ? constant0 : ( constant0 = make_nf1 ( lf_2sym , make_nf0 ( lf_1sym ) ) ) ) ) ) {
FUNC_EXIT_CONST ( constant1 , make_nf1 ( lf_2sym , make_nf0 ( lf_4sym ) ) ) ;
}
if ( term_equal ( arg0 , ( constant1 ? constant1 : ( constant1 = make_nf1 ( lf_2sym , make_nf0 ( lf_4sym ) ) ) ) ) ) {
FUNC_EXIT_CONST ( constant0 , make_nf1 ( lf_2sym , make_nf0 ( lf_1sym ) ) ) ;
}
FUNC_EXIT ( make_nf1 ( lf_3sym , arg0 ) ) ;
}
ATerm lf_11 ( ATerm arg0 , ATerm arg1 , ATerm arg2 ) {
CONS_ENTRY ( lf_11sym , ATmakeAppl ( lf_11sym , arg0 , arg1 , arg2 ) ) ;
CONS_EXIT ( make_nf3 ( lf_11sym , arg0 , arg1 , arg2 ) ) ;
}
ATerm lf_9 ( ATerm arg0 , ATerm arg1 , ATerm arg2 , ATerm arg3 ) {
CONS_ENTRY ( lf_9sym , ATmakeAppl ( lf_9sym , arg0 , arg1 , arg2 , arg3 ) ) ;
CONS_EXIT ( make_nf4 ( lf_9sym , arg0 , arg1 , arg2 , arg3 ) ) ;
}
ATerm lf_8 ( ATerm arg0 ) {
CONS_ENTRY ( lf_8sym , ATmakeAppl ( lf_8sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_8sym , arg0 ) ) ;
}
ATerm lf_list_7 ( ATerm arg0 ) {
CONS_ENTRY ( lf_list_7sym , ATmakeAppl ( lf_list_7sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_list_7sym , arg0 ) ) ;
}
ATerm lf_4 ( ) {
CONS_ENTRY ( lf_4sym , ATmakeAppl0 ( lf_4sym ) ) ;
CONS_EXIT ( make_nf0 ( lf_4sym ) ) ;
}
ATerm lf_2 ( ATerm arg0 ) {
CONS_ENTRY ( lf_2sym , ATmakeAppl ( lf_2sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_2sym , arg0 ) ) ;
}
ATerm lf_1 ( ) {
CONS_ENTRY ( lf_1sym , ATmakeAppl0 ( lf_1sym ) ) ;
CONS_EXIT ( make_nf0 ( lf_1sym ) ) ;
}
#ifdef ASF_MAIN
#ifdef TOOLBUS
#include <tb-asc-client.h>
#include <toolFindSortDefinition.tif.h>
#endif
int main(int argc, char *argv[])                         
{                                                        
  ATerm bottom;
  return asc_support_main(&bottom, argc, argv,           
                          register_FindSortDefinition,                   
                          resolve_FindSortDefinition,                    
                          init_FindSortDefinition
#ifdef TOOLBUS
                          , toolFindSortDefinition_handler
#endif
                          );}                                                        
#endif                                                   

