/**
 * This file is generated by /export/scratch1/jong/installed/bin/tifstoc. Do not edit!
 * Generated from tifs for tool 'toolFindSortDefinition' (prefix='')
 * Headerfile generated at Tue Jan 28 15:08:11 2003
 */

#ifndef _TOOLFINDSORTDEFINITION_H
#define _TOOLFINDSORTDEFINITION_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
ATerm rewrite(int conn, ATerm);
ATerm apply_rewrite(int conn, char *, char *, ATerm);
void rec_terminate(int conn, ATerm);
extern ATerm toolFindSortDefinition_handler(int conn, ATerm term);
extern ATerm toolFindSortDefinition_checker(int conn, ATerm sigs);

#endif
