/* This C code is generated by the asf compiler version 2.5 */

#include  "asc-support-me.h"
static Symbol lf_1sym ;
static ATerm lf_1 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol lf_2sym ;
static ATerm lf_2 ( ATerm arg1 ) ;
static Symbol lf_3sym ;
static ATerm lf_3 ( ATerm arg1 ) ;
static Symbol lt_4sym ;
static ATerm lt_4 ( ATerm arg1 ) ;
static Symbol lf_5sym ;
static ATerm lf_5 ( ATerm arg1 ) ;
static Symbol lf_6sym ;
static ATerm lf_6 ( ATerm arg1 ) ;
static Symbol lf_list_7sym ;
static ATerm lf_list_7 ( ) ;
void register_Remove_Var_Syntax ( ) {
lf_1sym = ATmakeSymbol ( "prod([lit(\"remove-var-syntax\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),cf(sort(\"ModuleName\")),cf(opt(layout)),lit(\",\"),cf(opt(layout)),cf(sort(\"SDF\")),cf(opt(layout)),lit(\")\")],cf(sort(\"SDF\")),no-attrs)"
 , 2 , ATtrue ) ;
ATprotectSymbol ( lf_1sym ) ;
lf_2sym = ATmakeSymbol ( "prod([lit(\"remove-var-syntax\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),cf(sort(\"SDF\")),cf(opt(layout)),lit(\")\")],cf(sort(\"SDF\")),no-attrs)" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_2sym ) ;
lf_3sym = ATmakeSymbol ( "prod([lit(\"variables\"),cf(opt(layout)),cf(sort(\"Productions\"))],cf(sort(\"Grammar\")),attrs([term(cons(\"variables\"))]))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_3sym ) ;
lt_4sym = ATmakeSymbol ( "prod([lit(\"remove\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),sort(\"***TRAVERSED***\"),cf(opt(layout)),lit(\")\")],sort(\"***TRAVERSED***\"),attrs([term(traversal(trafo,top-down,break)),id(\"languages/asf/removevariables/Remove-Var-Syntax\")]))" , 1 , ATtrue ) ;
ATprotectSymbol ( lt_4sym ) ;
lf_5sym = ATmakeSymbol ( "prod([lit(\"lexical\"),cf(opt(layout)),lit(\"variables\"),cf(opt(layout)),cf(sort(\"Productions\"))],cf(sort(\"Grammar\")),attrs([term(cons(\"lexical-variables\"))]))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_5sym ) ;
lf_6sym = ATmakeSymbol ( "prod([cf(iter-star(sort(\"Production\")))],cf(sort(\"Productions\")),no-attrs)" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_6sym ) ;
lf_list_7sym = ATmakeSymbol ( "list(cf(iter-star(sort(\"Production\"))))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_list_7sym ) ;
register_prod ( ATparse ( "list(cf(iter-star(sort(\"Production\"))))" ) , lf_list_7 , lf_list_7sym ) ;
register_prod ( ATparse ( "prod([cf(iter-star(sort(\"Production\")))],cf(sort(\"Productions\")),no-attrs)" ) , lf_6 , lf_6sym ) ;
register_prod ( ATparse ( "prod([lit(\"lexical\"),cf(opt(layout)),lit(\"variables\"),cf(opt(layout)),cf(sort(\"Productions\"))],cf(sort(\"Grammar\")),attrs([term(cons(\"lexical-variables\"))]))" ) , lf_5 , lf_5sym ) ;
register_prod ( ATparse ( "prod([lit(\"remove\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),sort(\"***TRAVERSED***\"),cf(opt(layout)),lit(\")\")],sort(\"***TRAVERSED***\"),attrs([term(traversal(trafo,top-down,break)),id(\"languages/asf/removevariables/Remove-Var-Syntax\")]))" ) , lt_4 , lt_4sym ) ;
register_prod ( ATparse ( "prod([lit(\"variables\"),cf(opt(layout)),cf(sort(\"Productions\"))],cf(sort(\"Grammar\")),attrs([term(cons(\"variables\"))]))" ) , lf_3 , lf_3sym ) ;
register_prod ( ATparse ( "prod([lit(\"remove-var-syntax\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),cf(sort(\"SDF\")),cf(opt(layout)),lit(\")\")],cf(sort(\"SDF\")),no-attrs)" ) , lf_2 , lf_2sym ) ;
register_prod ( ATparse ( "prod([lit(\"remove-var-syntax\"),cf(opt(layout)),lit(\"(\"),cf(opt(layout)),cf(sort(\"ModuleName\")),cf(opt(layout)),lit(\",\"),cf(opt(layout)),cf(sort(\"SDF\")),cf(opt(layout)),lit(\")\")],cf(sort(\"SDF\")),no-attrs)" ) , lf_1 , lf_1sym ) ;
}
void resolve_Remove_Var_Syntax ( ) {
}
static ATermTable table_lt_4 ;
static ATerm constant0 = NULL ;
static ATerm constant1 = NULL ;
void init_Remove_Var_Syntax ( ) {
create_table ( table_lt_4 , 0 ) ;
ATprotect ( & constant0 ) ;
ATprotect ( & constant1 ) ;
}
ATerm lf_1 ( ATerm arg0 , ATerm arg1 ) {
FUNC_ENTRY ( lf_1sym , ATmakeAppl ( lf_1sym , arg0 , arg1 ) ) ;
FUNC_EXIT ( lt_4 ( arg1 ) ) ;
FUNC_EXIT ( make_nf2 ( lf_1sym , arg0 , arg1 ) ) ;
}
ATerm lf_2 ( ATerm arg0 ) {
FUNC_ENTRY ( lf_2sym , ATmakeAppl ( lf_2sym , arg0 ) ) ;
FUNC_EXIT ( lt_4 ( arg0 ) ) ;
FUNC_EXIT ( make_nf1 ( lf_2sym , arg0 ) ) ;
}
ATerm lt_4 ( ATerm arg0 ) {
ATerm tmp [ 2 ] ;
FUNC_ENTRY ( lt_4sym , ATmakeAppl ( lt_4sym , arg0 ) ) ;
if ( check_sym ( arg0 , lf_5sym ) ) {
ATerm atmp_0_0 = arg_0 ( arg0 ) ;
if ( check_sym ( atmp_0_0 , lf_6sym ) ) {
ATerm atmp_0_0_0 = arg_0 ( atmp_0_0 ) ;
if ( check_sym ( atmp_0_0_0 , lf_list_7sym ) ) {
( tmp [ 1 ] = arg_0 ( atmp_0_0_0 ) ) ;
if ( not_empty_list ( tmp [ 1 ] ) ) {
FUNC_EXIT_CONST ( constant0 , make_nf1 ( lf_5sym , make_nf1 ( lf_6sym , make_nf1 ( lf_list_7sym , make_list ( null ( ) ) ) ) ) ) ;
}
}
}
}
if ( check_sym ( arg0 , lf_3sym ) ) {
ATerm atmp_0_0 = arg_0 ( arg0 ) ;
if ( check_sym ( atmp_0_0 , lf_6sym ) ) {
ATerm atmp_0_0_0 = arg_0 ( atmp_0_0 ) ;
if ( check_sym ( atmp_0_0_0 , lf_list_7sym ) ) {
( tmp [ 1 ] = arg_0 ( atmp_0_0_0 ) ) ;
if ( not_empty_list ( tmp [ 1 ] ) ) {
FUNC_EXIT_CONST ( constant1 , make_nf1 ( lf_3sym , make_nf1 ( lf_6sym , make_nf1 ( lf_list_7sym , make_list ( null ( ) ) ) ) ) ) ;
}
}
}
}
FUNC_EXIT ( call_kids_trafo ( lt_4 , arg0 , ATmakeList ( 0 ) ) ) ;
}
ATerm lf_list_7 ( ATerm arg0 ) {
CONS_ENTRY ( lf_list_7sym , ATmakeAppl ( lf_list_7sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_list_7sym , arg0 ) ) ;
}
ATerm lf_6 ( ATerm arg0 ) {
CONS_ENTRY ( lf_6sym , ATmakeAppl ( lf_6sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_6sym , arg0 ) ) ;
}
ATerm lf_5 ( ATerm arg0 ) {
CONS_ENTRY ( lf_5sym , ATmakeAppl ( lf_5sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_5sym , arg0 ) ) ;
}
ATerm lf_3 ( ATerm arg0 ) {
CONS_ENTRY ( lf_3sym , ATmakeAppl ( lf_3sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_3sym , arg0 ) ) ;
}
#ifdef ASF_MAIN
int main(int argc, char *argv[])                         
{                                                        
  ATerm bottom;
  setKeepAnnotations(ATfalse);
  return asc_support_main(&bottom, argc, argv,           
                          register_Remove_Var_Syntax,                   
                          resolve_Remove_Var_Syntax,                    
                          init_Remove_Var_Syntax, NULL, -1, ATfalse
, NULL);
}
#endif
