#!/bin/sh
USAGE="usage: $0 <name> <level> [port [host]]"
if test x$1 = x
then
  echo $USAGE
  exit 1
else
  NAME=$1
fi
if test x$2 = x
then
  echo $USAGE;
  exit 1
else
  LEVEL=$2
fi
if test x$3 = x
then
  PORT=8998
else 
  PORT=$3
fi
if test x$4 = x
then
  wish-adapter -wish wish4.0 -TB_PORT $PORT -TB_TOOL_NAME player -script heart-breaker.tcl \
		-script-args $NAME $LEVEL 
else
  wish-adapter -wish wish4.0 -TB_HOST $4 -TB_PORT $PORT -TB_TOOL_NAME player \
		-script heart-breaker.tcl -script-args $NAME $LEVEL
fi

