/*

    Meta-Environment - An environment for language prototyping.
    Copyright (C) 2001  Stichting Mathematisch Centrum, Amsterdam, 
    The Netherlands. 

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA

*/
/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
static Symbol lf_AUX_TermAsFixAccess4_1sym ;
static ATerm lf_AUX_TermAsFixAccess4_1 ( ATerm arg1 ) ;
static Symbol ef1sym ;
static funcptr ef1 ;
static Symbol ef9sym ;
static funcptr ef9 ;
static Symbol lf2sym ;
static ATerm lf2 ( ATerm arg1 ) ;
static Symbol ef13sym ;
static funcptr ef13 ;
static Symbol ef3sym ;
static funcptr ef3 ;
static Symbol ef5sym ;
static funcptr ef5 ;
static Symbol ef7sym ;
static funcptr ef7 ;
static Symbol ef8sym ;
static funcptr ef8 ;
static Symbol ef16sym ;
static funcptr ef16 ;
static Symbol ef2sym ;
static funcptr ef2 ;
static Symbol ef10sym ;
static funcptr ef10 ;
static Symbol ef12sym ;
static funcptr ef12 ;
static Symbol ef4sym ;
static funcptr ef4 ;
static Symbol ef6sym ;
static funcptr ef6 ;
static Symbol ef11sym ;
static funcptr ef11 ;
static Symbol ef14sym ;
static funcptr ef14 ;
static Symbol ef15sym ;
static funcptr ef15 ;
void register_AUX_TermAsFixAccess4 ( ) {
lf_AUX_TermAsFixAccess4_1sym = ATmakeSymbol ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"is-list-injection-production\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)"
 , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_TermAsFixAccess4_1sym ) ;
lf2sym = ATmakeSymbol ( "listtype(sort(\"CHAR\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf2sym ) ;
register_prod ( ATparse ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"is-list-injection-production\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) , lf_AUX_TermAsFixAccess4_1 , lf_AUX_TermAsFixAccess4_1sym ) ;
register_prod ( ATparse ( "listtype(sort(\"CHAR\"))" ) , lf2 , lf2sym ) ;
}
void resolve_AUX_TermAsFixAccess4 ( ) {
ef1 = lookup_func ( ATreadFromString ( "prod(id(\"ATerm-Booleans\"),w(\"\"),[ql(\"false\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef1sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerm-Booleans\"),w(\"\"),[ql(\"false\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef2 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"AFun\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerms\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef2sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"AFun\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerms\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef3 = lookup_func ( ATreadFromString ( "prod(id(\"AsFix-Constructors\"),w(\"\"),[ql(\"prod\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef3sym = lookup_sym ( ATreadFromString ( "prod(id(\"AsFix-Constructors\"),w(\"\"),[ql(\"prod\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef4 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATerm\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"ATerms\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)" ) ) ;
ef4sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATerm\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"ATerms\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)" ) ) ;
ef5 = lookup_func ( ATreadFromString ( "prod(id(\"AsFix-Constructors\"),w(\"\"),[ql(\"id\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef5sym = lookup_sym ( ATreadFromString ( "prod(id(\"AsFix-Constructors\"),w(\"\"),[ql(\"id\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef6 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATerm\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)" ) ) ;
ef6sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATerm\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)" ) ) ;
ef7 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATermList\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef7sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATermList\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef8 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[ql(\"[\"),w(\"\"),sort(\"ATerms\"),w(\"\"),ql(\"]\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATermList\"),w(\"\"),no-attrs)" ) ) ;
ef8sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[ql(\"[\"),w(\"\"),sort(\"ATerms\"),w(\"\"),ql(\"]\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATermList\"),w(\"\"),no-attrs)" ) ) ;
ef9 = lookup_func ( ATreadFromString ( "prod(id(\"ParseTree-Constructors\"),w(\"\"),[ql(\"iter-sep\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef9sym = lookup_sym ( ATreadFromString ( "prod(id(\"ParseTree-Constructors\"),w(\"\"),[ql(\"iter-sep\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef10 = lookup_func ( ATreadFromString ( "prod(id(\"ParseTree-Constructors\"),w(\"\"),[ql(\"l\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef10sym = lookup_sym ( ATreadFromString ( "prod(id(\"ParseTree-Constructors\"),w(\"\"),[ql(\"l\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef11 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"AFun\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef11sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"AFun\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef12 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"Literal\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef12sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"Literal\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef13 = lookup_func ( ATreadFromString ( "prod(id(\"GEN-LexConsFuncs\"),w(\"\"),[ql(\"literal\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"CHAR\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Literal\"),w(\"\"),no-attrs)" ) ) ;
ef13sym = lookup_sym ( ATreadFromString ( "prod(id(\"GEN-LexConsFuncs\"),w(\"\"),[ql(\"literal\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"CHAR\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Literal\"),w(\"\"),no-attrs)" ) ) ;
ef14 = lookup_func ( ATreadFromString ( "prod(id(\"AsFix-Constructors\"),w(\"\"),[ql(\"no-attrs\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef14sym = lookup_sym ( ATreadFromString ( "prod(id(\"AsFix-Constructors\"),w(\"\"),[ql(\"no-attrs\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef15 = lookup_func ( ATreadFromString ( "prod(id(\"ATerm-Booleans\"),w(\"\"),[ql(\"true\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef15sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerm-Booleans\"),w(\"\"),[ql(\"true\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef16 = lookup_func ( ATreadFromString ( "prod(id(\"ParseTree-Constructors\"),w(\"\"),[ql(\"iter\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef16sym = lookup_sym ( ATreadFromString ( "prod(id(\"ParseTree-Constructors\"),w(\"\"),[ql(\"iter\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
}
static ATerm constant0 = NULL ;
static ATerm constant1 = NULL ;
void init_AUX_TermAsFixAccess4 ( ) {
ATprotect ( & constant0 ) ;
ATprotect ( & constant1 ) ;
}
ATerm lf_AUX_TermAsFixAccess4_1 ( ATerm arg0 ) {
{
ATerm tmp [ 4 ] ;
FUNC_ENTRY ( lf_AUX_TermAsFixAccess4_1sym , ATmakeAppl ( lf_AUX_TermAsFixAccess4_1sym , arg0 ) ) ;
if ( check_sym ( arg0 , ef2sym ) ) {
{
ATerm atmp00 = arg_0 ( arg0 ) ;
if ( check_sym ( atmp00 , ef3sym ) ) {
{
ATerm atmp01 = arg_1 ( arg0 ) ;
if ( check_sym ( atmp01 , ef4sym ) ) {
{
ATerm atmp010 = arg_0 ( atmp01 ) ;
if ( check_sym ( atmp010 , ef2sym ) ) {
{
ATerm atmp0100 = arg_0 ( atmp010 ) ;
if ( check_sym ( atmp0100 , ef5sym ) ) {
{
ATerm atmp0101 = arg_1 ( atmp010 ) ;
if ( check_sym ( atmp0101 , ef6sym ) ) {
{
ATerm atmp01010 = arg_0 ( atmp0101 ) ;
{
ATerm atmp011 = arg_1 ( atmp01 ) ;
if ( check_sym ( atmp011 , ef4sym ) ) {
{
ATerm atmp0110 = arg_0 ( atmp011 ) ;
{
ATerm atmp0111 = arg_1 ( atmp011 ) ;
if ( check_sym ( atmp0111 , ef4sym ) ) {
{
ATerm atmp01110 = arg_0 ( atmp0111 ) ;
if ( check_sym ( atmp01110 , ef7sym ) ) {
{
ATerm atmp011100 = arg_0 ( atmp01110 ) ;
if ( check_sym ( atmp011100 , ef8sym ) ) {
{
ATerm atmp0111000 = arg_0 ( atmp011100 ) ;
if ( check_sym ( atmp0111000 , ef6sym ) ) {
{
ATerm atmp01110000 = arg_0 ( atmp0111000 ) ;
if ( check_sym ( atmp01110000 , ef2sym ) ) {
{
ATerm atmp011100000 = arg_0 ( atmp01110000 ) ;
if ( check_sym ( atmp011100000 , ef9sym ) ) {
{
ATerm atmp011100001 = arg_1 ( atmp01110000 ) ;
if ( check_sym ( atmp011100001 , ef4sym ) ) {
{
ATerm atmp0111000010 = arg_0 ( atmp011100001 ) ;
if ( check_sym ( atmp0111000010 , ef2sym ) ) {
{
ATerm atmp01110000100 = arg_0 ( atmp0111000010 ) ;
if ( check_sym ( atmp01110000100 , ef10sym ) ) {
{
ATerm atmp01110000101 = arg_1 ( atmp0111000010 ) ;
if ( check_sym ( atmp01110000101 , ef6sym ) ) {
{
ATerm atmp011100001010 = arg_0 ( atmp01110000101 ) ;
if ( check_sym ( atmp011100001010 , ef11sym ) ) {
{
ATerm atmp0111000010100 = arg_0 ( atmp011100001010 ) ;
if ( check_sym ( atmp0111000010100 , ef12sym ) ) {
{
ATerm atmp01110000101000 = arg_0 ( atmp0111000010100 ) ;
if ( check_sym ( atmp01110000101000 , ef13sym ) ) {
{
ATerm atmp011100001010000 = arg_0 ( atmp01110000101000 ) ;
if ( check_sym ( atmp011100001010000 , lf2sym ) ) {
{
ATerm atmp0111000010100000 = arg_0 ( atmp011100001010000 ) ;
{
ATerm atmp0111000011 = arg_1 ( atmp011100001 ) ;
if ( check_sym ( atmp0111000011 , ef4sym ) ) {
{
ATerm atmp01110000110 = arg_0 ( atmp0111000011 ) ;
{
ATerm atmp01110000111 = arg_1 ( atmp0111000011 ) ;
if ( check_sym ( atmp01110000111 , ef4sym ) ) {
{
ATerm atmp011100001110 = arg_0 ( atmp01110000111 ) ;
{
ATerm atmp011100001111 = arg_1 ( atmp01110000111 ) ;
if ( check_sym ( atmp011100001111 , ef4sym ) ) {
{
ATerm atmp0111000011110 = arg_0 ( atmp011100001111 ) ;
{
ATerm atmp0111000011111 = arg_1 ( atmp011100001111 ) ;
if ( check_sym ( atmp0111000011111 , ef4sym ) ) {
{
ATerm atmp01110000111110 = arg_0 ( atmp0111000011111 ) ;
{
ATerm atmp01110000111111 = arg_1 ( atmp0111000011111 ) ;
if ( check_sym ( atmp01110000111111 , ef4sym ) ) {
{
ATerm atmp011100001111110 = arg_0 ( atmp01110000111111 ) ;
{
ATerm atmp011100001111111 = arg_1 ( atmp01110000111111 ) ;
if ( check_sym ( atmp011100001111111 , ef4sym ) ) {
{
ATerm atmp0111000011111110 = arg_0 ( atmp011100001111111 ) ;
if ( check_sym ( atmp0111000011111110 , ef2sym ) ) {
{
ATerm atmp01110000111111100 = arg_0 ( atmp0111000011111110 ) ;
if ( check_sym ( atmp01110000111111100 , ef10sym ) ) {
{
ATerm atmp01110000111111101 = arg_1 ( atmp0111000011111110 ) ;
if ( check_sym ( atmp01110000111111101 , ef6sym ) ) {
{
ATerm atmp011100001111111010 = arg_0 ( atmp01110000111111101 ) ;
if ( check_sym ( atmp011100001111111010 , ef11sym ) ) {
{
ATerm atmp0111000011111110100 = arg_0 ( atmp011100001111111010 ) ;
if ( check_sym ( atmp0111000011111110100 , ef12sym ) ) {
{
ATerm atmp01110000111111101000 = arg_0 ( atmp0111000011111110100 ) ;
if ( check_sym ( atmp01110000111111101000 , ef13sym ) ) {
{
ATerm atmp011100001111111010000 = arg_0 ( atmp01110000111111101000 ) ;
if ( check_sym ( atmp011100001111111010000 , lf2sym ) ) {
{
ATerm atmp0111000011111110100000 = arg_0 ( atmp011100001111111010000 ) ;
{
ATerm atmp0111000011111111 = arg_1 ( atmp011100001111111 ) ;
if ( check_sym ( atmp0111000011111111 , ef4sym ) ) {
{
ATerm atmp01110000111111110 = arg_0 ( atmp0111000011111111 ) ;
{
ATerm atmp01110000111111111 = arg_1 ( atmp0111000011111111 ) ;
if ( check_sym ( atmp01110000111111111 , ef6sym ) ) {
{
ATerm atmp011100001111111110 = arg_0 ( atmp01110000111111111 ) ;
if ( check_sym ( atmp011100001111111110 , ef2sym ) ) {
{
ATerm atmp0111000011111111100 = arg_0 ( atmp011100001111111110 ) ;
if ( check_sym ( atmp0111000011111111100 , ef10sym ) ) {
{
ATerm atmp0111000011111111101 = arg_1 ( atmp011100001111111110 ) ;
if ( check_sym ( atmp0111000011111111101 , ef6sym ) ) {
{
ATerm atmp01110000111111111010 = arg_0 ( atmp0111000011111111101 ) ;
if ( check_sym ( atmp01110000111111111010 , ef11sym ) ) {
{
ATerm atmp011100001111111110100 = arg_0 ( atmp01110000111111111010 ) ;
if ( check_sym ( atmp011100001111111110100 , ef12sym ) ) {
{
ATerm atmp0111000011111111101000 = arg_0 ( atmp011100001111111110100 ) ;
{
ATerm atmp01111 = arg_1 ( atmp0111 ) ;
if ( check_sym ( atmp01111 , ef4sym ) ) {
{
ATerm atmp011110 = arg_0 ( atmp01111 ) ;
{
ATerm atmp011111 = arg_1 ( atmp01111 ) ;
if ( check_sym ( atmp011111 , ef4sym ) ) {
{
ATerm atmp0111110 = arg_0 ( atmp011111 ) ;
if ( check_sym ( atmp0111110 , ef2sym ) ) {
{
ATerm atmp01111100 = arg_0 ( atmp0111110 ) ;
if ( check_sym ( atmp01111100 , ef10sym ) ) {
{
ATerm atmp01111101 = arg_1 ( atmp0111110 ) ;
if ( check_sym ( atmp01111101 , ef6sym ) ) {
{
ATerm atmp011111010 = arg_0 ( atmp01111101 ) ;
if ( check_sym ( atmp011111010 , ef11sym ) ) {
{
ATerm atmp0111110100 = arg_0 ( atmp011111010 ) ;
if ( check_sym ( atmp0111110100 , ef12sym ) ) {
{
ATerm atmp01111101000 = arg_0 ( atmp0111110100 ) ;
{
ATerm atmp0111111 = arg_1 ( atmp011111 ) ;
if ( check_sym ( atmp0111111 , ef4sym ) ) {
{
ATerm atmp01111110 = arg_0 ( atmp0111111 ) ;
{
ATerm atmp01111111 = arg_1 ( atmp0111111 ) ;
if ( check_sym ( atmp01111111 , ef4sym ) ) {
{
ATerm atmp011111110 = arg_0 ( atmp01111111 ) ;
{
ATerm atmp011111111 = arg_1 ( atmp01111111 ) ;
if ( check_sym ( atmp011111111 , ef4sym ) ) {
{
ATerm atmp0111111110 = arg_0 ( atmp011111111 ) ;
{
ATerm atmp0111111111 = arg_1 ( atmp011111111 ) ;
if ( check_sym ( atmp0111111111 , ef6sym ) ) {
{
ATerm atmp01111111110 = arg_0 ( atmp0111111111 ) ;
if ( check_sym ( atmp01111111110 , ef11sym ) ) {
{
ATerm atmp011111111100 = arg_0 ( atmp01111111110 ) ;
if ( check_sym ( atmp011111111100 , ef14sym ) ) {
if ( not_empty_list ( atmp0111000010100000 ) ) {
if ( term_equal ( list_head ( atmp0111000010100000 ) , make_char ( 34 ) ) ) {
( tmp [ 0 ] = list_tail ( atmp0111000010100000 ) ) ;
if ( not_empty_list ( tmp [ 0 ] ) ) {
if ( term_equal ( list_head ( tmp [ 0 ] ) , make_char ( 123 ) ) ) {
( tmp [ 1 ] = list_tail ( tmp [ 0 ] ) ) ;
if ( is_single_element ( tmp [ 1 ] ) ) {
if ( term_equal ( list_head ( tmp [ 1 ] ) , make_char ( 34 ) ) ) {
if ( not_empty_list ( atmp0111000011111110100000 ) ) {
if ( term_equal ( list_head ( atmp0111000011111110100000 ) , make_char ( 34 ) ) ) {
( tmp [ 2 ] = list_tail ( atmp0111000011111110100000 ) ) ;
if ( not_empty_list ( tmp [ 2 ] ) ) {
if ( term_equal ( list_head ( tmp [ 2 ] ) , make_char ( 125 ) ) ) {
( tmp [ 3 ] = list_tail ( tmp [ 2 ] ) ) ;
if ( is_single_element ( tmp [ 3 ] ) ) {
if ( term_equal ( list_head ( tmp [ 3 ] ) , make_char ( 34 ) ) ) {
FUNC_EXIT_CONST ( constant0 , ( * ef15 ) ( ) ) ;
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
{
ATerm atmp011100000 = arg_0 ( atmp01110000 ) ;
if ( check_sym ( atmp011100000 , ef16sym ) ) {
{
ATerm atmp011100001 = arg_1 ( atmp01110000 ) ;
if ( check_sym ( atmp011100001 , ef4sym ) ) {
{
ATerm atmp0111000010 = arg_0 ( atmp011100001 ) ;
{
ATerm atmp0111000011 = arg_1 ( atmp011100001 ) ;
if ( check_sym ( atmp0111000011 , ef4sym ) ) {
{
ATerm atmp01110000110 = arg_0 ( atmp0111000011 ) ;
{
ATerm atmp01110000111 = arg_1 ( atmp0111000011 ) ;
if ( check_sym ( atmp01110000111 , ef6sym ) ) {
{
ATerm atmp011100001110 = arg_0 ( atmp01110000111 ) ;
if ( check_sym ( atmp011100001110 , ef2sym ) ) {
{
ATerm atmp0111000011100 = arg_0 ( atmp011100001110 ) ;
if ( check_sym ( atmp0111000011100 , ef10sym ) ) {
{
ATerm atmp0111000011101 = arg_1 ( atmp011100001110 ) ;
if ( check_sym ( atmp0111000011101 , ef6sym ) ) {
{
ATerm atmp01110000111010 = arg_0 ( atmp0111000011101 ) ;
if ( check_sym ( atmp01110000111010 , ef11sym ) ) {
{
ATerm atmp011100001110100 = arg_0 ( atmp01110000111010 ) ;
if ( check_sym ( atmp011100001110100 , ef12sym ) ) {
{
ATerm atmp0111000011101000 = arg_0 ( atmp011100001110100 ) ;
{
ATerm atmp01111 = arg_1 ( atmp0111 ) ;
if ( check_sym ( atmp01111 , ef4sym ) ) {
{
ATerm atmp011110 = arg_0 ( atmp01111 ) ;
{
ATerm atmp011111 = arg_1 ( atmp01111 ) ;
if ( check_sym ( atmp011111 , ef4sym ) ) {
{
ATerm atmp0111110 = arg_0 ( atmp011111 ) ;
if ( check_sym ( atmp0111110 , ef2sym ) ) {
{
ATerm atmp01111100 = arg_0 ( atmp0111110 ) ;
if ( check_sym ( atmp01111100 , ef10sym ) ) {
{
ATerm atmp01111101 = arg_1 ( atmp0111110 ) ;
if ( check_sym ( atmp01111101 , ef6sym ) ) {
{
ATerm atmp011111010 = arg_0 ( atmp01111101 ) ;
if ( check_sym ( atmp011111010 , ef11sym ) ) {
{
ATerm atmp0111110100 = arg_0 ( atmp011111010 ) ;
if ( check_sym ( atmp0111110100 , ef12sym ) ) {
{
ATerm atmp01111101000 = arg_0 ( atmp0111110100 ) ;
{
ATerm atmp0111111 = arg_1 ( atmp011111 ) ;
if ( check_sym ( atmp0111111 , ef4sym ) ) {
{
ATerm atmp01111110 = arg_0 ( atmp0111111 ) ;
{
ATerm atmp01111111 = arg_1 ( atmp0111111 ) ;
if ( check_sym ( atmp01111111 , ef4sym ) ) {
{
ATerm atmp011111110 = arg_0 ( atmp01111111 ) ;
{
ATerm atmp011111111 = arg_1 ( atmp01111111 ) ;
if ( check_sym ( atmp011111111 , ef4sym ) ) {
{
ATerm atmp0111111110 = arg_0 ( atmp011111111 ) ;
{
ATerm atmp0111111111 = arg_1 ( atmp011111111 ) ;
if ( check_sym ( atmp0111111111 , ef6sym ) ) {
{
ATerm atmp01111111110 = arg_0 ( atmp0111111111 ) ;
if ( check_sym ( atmp01111111110 , ef11sym ) ) {
{
ATerm atmp011111111100 = arg_0 ( atmp01111111110 ) ;
if ( check_sym ( atmp011111111100 , ef14sym ) ) {
FUNC_EXIT_CONST ( constant0 , ( * ef15 ) ( ) ) ;
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
FUNC_EXIT_CONST ( constant1 , ( * ef1 ) ( ) ) ;
FUNC_EXIT ( make_nf1 ( lf_AUX_TermAsFixAccess4_1sym , arg0 ) ) ;
}
}
ATerm lf2 ( ATerm arg0 ) {
CONS_ENTRY ( lf2sym , ATmakeAppl ( lf2sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf2sym , arg0 ) ) ;
}

