/*

    Meta-Environment - An environment for language prototyping.
    Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam, 
    The Netherlands. 

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA

*/
/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
static Symbol lf_AUX_TermAsFixAccess58_1sym ;
static ATerm lf_AUX_TermAsFixAccess58_1 ( ATerm arg1 ) ;
static Symbol ef11sym ;
static funcptr ef11 ;
static Symbol ef13sym ;
static funcptr ef13 ;
static Symbol ef15sym ;
static funcptr ef15 ;
static Symbol ef2sym ;
static funcptr ef2 ;
static Symbol ef6sym ;
static funcptr ef6 ;
static Symbol ef7sym ;
static funcptr ef7 ;
static Symbol ef16sym ;
static funcptr ef16 ;
static Symbol ef12sym ;
static funcptr ef12 ;
static Symbol ef14sym ;
static funcptr ef14 ;
static Symbol ef3sym ;
static funcptr ef3 ;
static Symbol ef1sym ;
static funcptr ef1 ;
static Symbol ef17sym ;
static funcptr ef17 ;
static Symbol ef8sym ;
static funcptr ef8 ;
static Symbol ef9sym ;
static funcptr ef9 ;
static Symbol lf2sym ;
static ATerm lf2 ( ATerm arg1 ) ;
static Symbol ef10sym ;
static funcptr ef10 ;
static Symbol ef4sym ;
static funcptr ef4 ;
static Symbol ef5sym ;
static funcptr ef5 ;
void register_AUX_TermAsFixAccess58 ( ) {
lf_AUX_TermAsFixAccess58_1sym = ATmakeSymbol ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"term-get-args-prod\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATermList\"),w(\"\"),no-attrs)"
 , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_TermAsFixAccess58_1sym ) ;
lf2sym = ATmakeSymbol ( "listtype(sort(\"CHAR\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf2sym ) ;
register_prod ( ATparse ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"term-get-args-prod\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATermList\"),w(\"\"),no-attrs)" ) , lf_AUX_TermAsFixAccess58_1 , lf_AUX_TermAsFixAccess58_1sym ) ;
register_prod ( ATparse ( "listtype(sort(\"CHAR\"))" ) , lf2 , lf2sym ) ;
}
void resolve_AUX_TermAsFixAccess58 ( ) {
ef1 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"AFun\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerms\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef1sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"AFun\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerms\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef2 = lookup_func ( ATreadFromString ( "prod(id(\"AsFix-Constructors\"),w(\"\"),[ql(\"appl\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef2sym = lookup_sym ( ATreadFromString ( "prod(id(\"AsFix-Constructors\"),w(\"\"),[ql(\"appl\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef3 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATerm\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"ATerms\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)" ) ) ;
ef3sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATerm\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"ATerms\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)" ) ) ;
ef4 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATerm\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)" ) ) ;
ef4sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATerm\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)" ) ) ;
ef5 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATermList\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef5sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"ATermList\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef6 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[ql(\"[\"),w(\"\"),sort(\"ATerms\"),w(\"\"),ql(\"]\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATermList\"),w(\"\"),no-attrs)" ) ) ;
ef6sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[ql(\"[\"),w(\"\"),sort(\"ATerms\"),w(\"\"),ql(\"]\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATermList\"),w(\"\"),no-attrs)" ) ) ;
ef7 = lookup_func ( ATreadFromString ( "prod(id(\"ParseTree-Constructors\"),w(\"\"),[ql(\"l\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef7sym = lookup_sym ( ATreadFromString ( "prod(id(\"ParseTree-Constructors\"),w(\"\"),[ql(\"l\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef8 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"AFun\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef8sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"AFun\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef9 = lookup_func ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"Literal\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef9sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerms\"),w(\"\"),[sort(\"Literal\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef10 = lookup_func ( ATreadFromString ( "prod(id(\"GEN-LexConsFuncs\"),w(\"\"),[ql(\"literal\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"CHAR\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Literal\"),w(\"\"),no-attrs)" ) ) ;
ef10sym = lookup_sym ( ATreadFromString ( "prod(id(\"GEN-LexConsFuncs\"),w(\"\"),[ql(\"literal\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"CHAR\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Literal\"),w(\"\"),no-attrs)" ) ) ;
ef11 = lookup_func ( ATreadFromString ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"is-production-prod\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef11sym = lookup_sym ( ATreadFromString ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"is-production-prod\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef12 = lookup_func ( ATreadFromString ( "prod(id(\"ATerm-Booleans\"),w(\"\"),[ql(\"true\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef12sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerm-Booleans\"),w(\"\"),[ql(\"true\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef13 = lookup_func ( ATreadFromString ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"is-symbols-prod\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef13sym = lookup_sym ( ATreadFromString ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"is-symbols-prod\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef14 = lookup_func ( ATreadFromString ( "prod(id(\"AsFix-Constructors\"),w(\"\"),[ql(\"list\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef14sym = lookup_sym ( ATreadFromString ( "prod(id(\"AsFix-Constructors\"),w(\"\"),[ql(\"list\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef15 = lookup_func ( ATreadFromString ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"is-symbol-iter\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef15sym = lookup_sym ( ATreadFromString ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"is-symbol-iter\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef16 = lookup_func ( ATreadFromString ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"is-prefix-production-prod\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef16sym = lookup_sym ( ATreadFromString ( "prod(id(\"TermAsFixAccess\"),w(\"\"),[ql(\"is-prefix-production-prod\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef17 = lookup_func ( ATreadFromString ( "prod(id(\"ParseTree-Constructors\"),w(\"\"),[ql(\"w\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef17sym = lookup_sym ( ATreadFromString ( "prod(id(\"ParseTree-Constructors\"),w(\"\"),[ql(\"w\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
}
static ATerm constant0 = NULL ;
static ATerm constant1 = NULL ;
static ATerm constant2 = NULL ;
static ATerm constant3 = NULL ;
void init_AUX_TermAsFixAccess58 ( ) {
ATprotect ( & constant0 ) ;
ATprotect ( & constant1 ) ;
ATprotect ( & constant2 ) ;
ATprotect ( & constant3 ) ;
}
ATerm lf_AUX_TermAsFixAccess58_1 ( ATerm arg0 ) {
{
ATerm tmp [ 23 ] ;
FUNC_ENTRY ( lf_AUX_TermAsFixAccess58_1sym , ATmakeAppl ( lf_AUX_TermAsFixAccess58_1sym , arg0 ) ) ;
if ( check_sym ( arg0 , ef1sym ) ) {
{
ATerm atmp00 = arg_0 ( arg0 ) ;
if ( check_sym ( atmp00 , ef2sym ) ) {
{
ATerm atmp01 = arg_1 ( arg0 ) ;
if ( check_sym ( atmp01 , ef3sym ) ) {
{
ATerm atmp010 = arg_0 ( atmp01 ) ;
{
ATerm atmp011 = arg_1 ( atmp01 ) ;
if ( check_sym ( atmp011 , ef3sym ) ) {
{
ATerm atmp0110 = arg_0 ( atmp011 ) ;
{
ATerm atmp0111 = arg_1 ( atmp011 ) ;
if ( check_sym ( atmp0111 , ef4sym ) ) {
{
ATerm atmp01110 = arg_0 ( atmp0111 ) ;
if ( check_sym ( atmp01110 , ef5sym ) ) {
{
ATerm atmp011100 = arg_0 ( atmp01110 ) ;
if ( check_sym ( atmp011100 , ef6sym ) ) {
{
ATerm atmp0111000 = arg_0 ( atmp011100 ) ;
if ( check_sym ( atmp0111000 , ef3sym ) ) {
{
ATerm atmp01110000 = arg_0 ( atmp0111000 ) ;
{
ATerm atmp01110001 = arg_1 ( atmp0111000 ) ;
if ( check_sym ( atmp01110001 , ef3sym ) ) {
{
ATerm atmp011100010 = arg_0 ( atmp01110001 ) ;
{
ATerm atmp011100011 = arg_1 ( atmp01110001 ) ;
if ( check_sym ( atmp011100011 , ef3sym ) ) {
{
ATerm atmp0111000110 = arg_0 ( atmp011100011 ) ;
if ( check_sym ( atmp0111000110 , ef1sym ) ) {
{
ATerm atmp01110001100 = arg_0 ( atmp0111000110 ) ;
if ( check_sym ( atmp01110001100 , ef7sym ) ) {
{
ATerm atmp01110001101 = arg_1 ( atmp0111000110 ) ;
if ( check_sym ( atmp01110001101 , ef4sym ) ) {
{
ATerm atmp011100011010 = arg_0 ( atmp01110001101 ) ;
if ( check_sym ( atmp011100011010 , ef8sym ) ) {
{
ATerm atmp0111000110100 = arg_0 ( atmp011100011010 ) ;
if ( check_sym ( atmp0111000110100 , ef9sym ) ) {
{
ATerm atmp01110001101000 = arg_0 ( atmp0111000110100 ) ;
if ( check_sym ( atmp01110001101000 , ef10sym ) ) {
{
ATerm atmp011100011010000 = arg_0 ( atmp01110001101000 ) ;
if ( check_sym ( atmp011100011010000 , lf2sym ) ) {
{
ATerm atmp0111000110100000 = arg_0 ( atmp011100011010000 ) ;
{
ATerm atmp0111000111 = arg_1 ( atmp011100011 ) ;
if ( check_sym ( atmp0111000111 , ef3sym ) ) {
{
ATerm atmp01110001110 = arg_0 ( atmp0111000111 ) ;
{
ATerm atmp01110001111 = arg_1 ( atmp0111000111 ) ;
if ( check_sym ( atmp01110001111 , ef3sym ) ) {
{
ATerm atmp011100011110 = arg_0 ( atmp01110001111 ) ;
{
ATerm atmp011100011111 = arg_1 ( atmp01110001111 ) ;
if ( check_sym ( atmp011100011111 , ef3sym ) ) {
{
ATerm atmp0111000111110 = arg_0 ( atmp011100011111 ) ;
{
ATerm atmp0111000111111 = arg_1 ( atmp011100011111 ) ;
if ( check_sym ( atmp0111000111111 , ef4sym ) ) {
{
ATerm atmp01110001111110 = arg_0 ( atmp0111000111111 ) ;
if ( not_empty_list ( atmp0111000110100000 ) ) {
if ( term_equal ( list_head ( atmp0111000110100000 ) , make_char ( 34 ) ) ) {
( tmp [ 0 ] = list_tail ( atmp0111000110100000 ) ) ;
if ( not_empty_list ( tmp [ 0 ] ) ) {
if ( term_equal ( list_head ( tmp [ 0 ] ) , make_char ( 45 ) ) ) {
( tmp [ 1 ] = list_tail ( tmp [ 0 ] ) ) ;
if ( not_empty_list ( tmp [ 1 ] ) ) {
if ( term_equal ( list_head ( tmp [ 1 ] ) , make_char ( 62 ) ) ) {
( tmp [ 2 ] = list_tail ( tmp [ 1 ] ) ) ;
if ( is_single_element ( tmp [ 2 ] ) ) {
if ( term_equal ( list_head ( tmp [ 2 ] ) , make_char ( 34 ) ) ) {
if ( term_equal ( ( * ef11 ) ( atmp010 ) , ( constant0 ? constant0 : ( constant0 = ( * ef12 ) ( ) ) ) ) ) {
if ( check_sym ( atmp01110000 , ef1sym ) ) {
( tmp [ 3 ] = arg_0 ( atmp01110000 ) ) ;
( tmp [ 4 ] = arg_1 ( atmp01110000 ) ) ;
if ( term_equal ( tmp [ 3 ] , ( constant1 ? constant1 : ( constant1 = ( * ef2 ) ( ) ) ) ) ) {
if ( check_sym ( tmp [ 4 ] , ef3sym ) ) {
( tmp [ 5 ] = arg_0 ( tmp [ 4 ] ) ) ;
( tmp [ 6 ] = arg_1 ( tmp [ 4 ] ) ) ;
if ( check_sym ( tmp [ 6 ] , ef3sym ) ) {
( tmp [ 7 ] = arg_0 ( tmp [ 6 ] ) ) ;
( tmp [ 8 ] = arg_1 ( tmp [ 6 ] ) ) ;
if ( check_sym ( tmp [ 8 ] , ef4sym ) ) {
( tmp [ 9 ] = arg_0 ( tmp [ 8 ] ) ) ;
if ( check_sym ( tmp [ 9 ] , ef5sym ) ) {
( tmp [ 10 ] = arg_0 ( tmp [ 9 ] ) ) ;
if ( check_sym ( tmp [ 10 ] , ef6sym ) ) {
( tmp [ 11 ] = arg_0 ( tmp [ 10 ] ) ) ;
if ( check_sym ( tmp [ 11 ] , ef4sym ) ) {
( tmp [ 12 ] = arg_0 ( tmp [ 11 ] ) ) ;
if ( term_equal ( ( * ef13 ) ( tmp [ 5 ] ) , ( constant0 ? constant0 : ( constant0 = ( * ef12 ) ( ) ) ) ) ) {
if ( check_sym ( tmp [ 12 ] , ef1sym ) ) {
( tmp [ 13 ] = arg_0 ( tmp [ 12 ] ) ) ;
( tmp [ 14 ] = arg_1 ( tmp [ 12 ] ) ) ;
if ( term_equal ( tmp [ 13 ] , ( constant2 ? constant2 : ( constant2 = ( * ef14 ) ( ) ) ) ) ) {
if ( check_sym ( tmp [ 14 ] , ef3sym ) ) {
( tmp [ 15 ] = arg_0 ( tmp [ 14 ] ) ) ;
( tmp [ 16 ] = arg_1 ( tmp [ 14 ] ) ) ;
if ( check_sym ( tmp [ 16 ] , ef3sym ) ) {
( tmp [ 17 ] = arg_0 ( tmp [ 16 ] ) ) ;
( tmp [ 18 ] = arg_1 ( tmp [ 16 ] ) ) ;
if ( check_sym ( tmp [ 18 ] , ef4sym ) ) {
( tmp [ 19 ] = arg_0 ( tmp [ 18 ] ) ) ;
if ( check_sym ( tmp [ 19 ] , ef5sym ) ) {
( tmp [ 20 ] = arg_0 ( tmp [ 19 ] ) ) ;
if ( term_equal ( ( * ef15 ) ( tmp [ 15 ] ) , ( constant0 ? constant0 : ( constant0 = ( * ef12 ) ( ) ) ) ) ) {
FUNC_EXIT ( tmp [ 20 ] ) ;
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
{
ATerm atmp0111000111111 = arg_1 ( atmp011100011111 ) ;
if ( check_sym ( atmp0111000111111 , ef3sym ) ) {
{
ATerm atmp01110001111110 = arg_0 ( atmp0111000111111 ) ;
if ( check_sym ( atmp01110001111110 , ef1sym ) ) {
{
ATerm atmp011100011111100 = arg_0 ( atmp01110001111110 ) ;
if ( check_sym ( atmp011100011111100 , ef7sym ) ) {
{
ATerm atmp011100011111101 = arg_1 ( atmp01110001111110 ) ;
if ( check_sym ( atmp011100011111101 , ef4sym ) ) {
{
ATerm atmp0111000111111010 = arg_0 ( atmp011100011111101 ) ;
if ( check_sym ( atmp0111000111111010 , ef8sym ) ) {
{
ATerm atmp01110001111110100 = arg_0 ( atmp0111000111111010 ) ;
if ( check_sym ( atmp01110001111110100 , ef9sym ) ) {
{
ATerm atmp011100011111101000 = arg_0 ( atmp01110001111110100 ) ;
if ( check_sym ( atmp011100011111101000 , ef10sym ) ) {
{
ATerm atmp0111000111111010000 = arg_0 ( atmp011100011111101000 ) ;
if ( check_sym ( atmp0111000111111010000 , lf2sym ) ) {
{
ATerm atmp01110001111110100000 = arg_0 ( atmp0111000111111010000 ) ;
{
ATerm atmp01110001111111 = arg_1 ( atmp0111000111111 ) ;
if ( check_sym ( atmp01110001111111 , ef3sym ) ) {
{
ATerm atmp011100011111110 = arg_0 ( atmp01110001111111 ) ;
{
ATerm atmp011100011111111 = arg_1 ( atmp01110001111111 ) ;
if ( check_sym ( atmp011100011111111 , ef3sym ) ) {
{
ATerm atmp0111000111111110 = arg_0 ( atmp011100011111111 ) ;
if ( check_sym ( atmp0111000111111110 , ef1sym ) ) {
{
ATerm atmp01110001111111100 = arg_0 ( atmp0111000111111110 ) ;
if ( check_sym ( atmp01110001111111100 , ef7sym ) ) {
{
ATerm atmp01110001111111101 = arg_1 ( atmp0111000111111110 ) ;
if ( check_sym ( atmp01110001111111101 , ef4sym ) ) {
{
ATerm atmp011100011111111010 = arg_0 ( atmp01110001111111101 ) ;
if ( check_sym ( atmp011100011111111010 , ef8sym ) ) {
{
ATerm atmp0111000111111110100 = arg_0 ( atmp011100011111111010 ) ;
if ( check_sym ( atmp0111000111111110100 , ef9sym ) ) {
{
ATerm atmp01110001111111101000 = arg_0 ( atmp0111000111111110100 ) ;
if ( check_sym ( atmp01110001111111101000 , ef10sym ) ) {
{
ATerm atmp011100011111111010000 = arg_0 ( atmp01110001111111101000 ) ;
if ( check_sym ( atmp011100011111111010000 , lf2sym ) ) {
{
ATerm atmp0111000111111110100000 = arg_0 ( atmp011100011111111010000 ) ;
{
ATerm atmp0111000111111111 = arg_1 ( atmp011100011111111 ) ;
if ( check_sym ( atmp0111000111111111 , ef3sym ) ) {
{
ATerm atmp01110001111111110 = arg_0 ( atmp0111000111111111 ) ;
{
ATerm atmp01110001111111111 = arg_1 ( atmp0111000111111111 ) ;
if ( check_sym ( atmp01110001111111111 , ef3sym ) ) {
{
ATerm atmp011100011111111110 = arg_0 ( atmp01110001111111111 ) ;
{
ATerm atmp011100011111111111 = arg_1 ( atmp01110001111111111 ) ;
if ( check_sym ( atmp011100011111111111 , ef3sym ) ) {
{
ATerm atmp0111000111111111110 = arg_0 ( atmp011100011111111111 ) ;
{
ATerm atmp0111000111111111111 = arg_1 ( atmp011100011111111111 ) ;
if ( check_sym ( atmp0111000111111111111 , ef4sym ) ) {
{
ATerm atmp01110001111111111110 = arg_0 ( atmp0111000111111111111 ) ;
if ( not_empty_list ( atmp0111000110100000 ) ) {
if ( term_equal ( list_head ( atmp0111000110100000 ) , make_char ( 34 ) ) ) {
( tmp [ 0 ] = list_tail ( atmp0111000110100000 ) ) ;
if ( not_empty_list ( tmp [ 0 ] ) ) {
if ( term_equal ( list_head ( tmp [ 0 ] ) , make_char ( 40 ) ) ) {
( tmp [ 1 ] = list_tail ( tmp [ 0 ] ) ) ;
if ( is_single_element ( tmp [ 1 ] ) ) {
if ( term_equal ( list_head ( tmp [ 1 ] ) , make_char ( 34 ) ) ) {
if ( not_empty_list ( atmp01110001111110100000 ) ) {
if ( term_equal ( list_head ( atmp01110001111110100000 ) , make_char ( 34 ) ) ) {
( tmp [ 2 ] = list_tail ( atmp01110001111110100000 ) ) ;
if ( not_empty_list ( tmp [ 2 ] ) ) {
if ( term_equal ( list_head ( tmp [ 2 ] ) , make_char ( 41 ) ) ) {
( tmp [ 3 ] = list_tail ( tmp [ 2 ] ) ) ;
if ( is_single_element ( tmp [ 3 ] ) ) {
if ( term_equal ( list_head ( tmp [ 3 ] ) , make_char ( 34 ) ) ) {
if ( not_empty_list ( atmp0111000111111110100000 ) ) {
if ( term_equal ( list_head ( atmp0111000111111110100000 ) , make_char ( 34 ) ) ) {
( tmp [ 4 ] = list_tail ( atmp0111000111111110100000 ) ) ;
if ( not_empty_list ( tmp [ 4 ] ) ) {
if ( term_equal ( list_head ( tmp [ 4 ] ) , make_char ( 45 ) ) ) {
( tmp [ 5 ] = list_tail ( tmp [ 4 ] ) ) ;
if ( not_empty_list ( tmp [ 5 ] ) ) {
if ( term_equal ( list_head ( tmp [ 5 ] ) , make_char ( 62 ) ) ) {
( tmp [ 6 ] = list_tail ( tmp [ 5 ] ) ) ;
if ( is_single_element ( tmp [ 6 ] ) ) {
if ( term_equal ( list_head ( tmp [ 6 ] ) , make_char ( 34 ) ) ) {
if ( term_equal ( ( * ef16 ) ( atmp010 ) , ( constant0 ? constant0 : ( constant0 = ( * ef12 ) ( ) ) ) ) ) {
if ( check_sym ( atmp011100011110 , ef1sym ) ) {
( tmp [ 7 ] = arg_0 ( atmp011100011110 ) ) ;
( tmp [ 8 ] = arg_1 ( atmp011100011110 ) ) ;
if ( term_equal ( tmp [ 7 ] , ( constant2 ? constant2 : ( constant2 = ( * ef14 ) ( ) ) ) ) ) {
if ( check_sym ( tmp [ 8 ] , ef3sym ) ) {
( tmp [ 9 ] = arg_0 ( tmp [ 8 ] ) ) ;
( tmp [ 10 ] = arg_1 ( tmp [ 8 ] ) ) ;
if ( check_sym ( tmp [ 10 ] , ef3sym ) ) {
( tmp [ 11 ] = arg_0 ( tmp [ 10 ] ) ) ;
( tmp [ 12 ] = arg_1 ( tmp [ 10 ] ) ) ;
if ( check_sym ( tmp [ 11 ] , ef1sym ) ) {
( tmp [ 13 ] = arg_0 ( tmp [ 11 ] ) ) ;
( tmp [ 14 ] = arg_1 ( tmp [ 11 ] ) ) ;
if ( term_equal ( tmp [ 13 ] , ( constant3 ? constant3 : ( constant3 = ( * ef17 ) ( ) ) ) ) ) {
if ( check_sym ( tmp [ 14 ] , ef4sym ) ) {
( tmp [ 15 ] = arg_0 ( tmp [ 14 ] ) ) ;
if ( check_sym ( tmp [ 15 ] , ef8sym ) ) {
( tmp [ 16 ] = arg_0 ( tmp [ 15 ] ) ) ;
if ( check_sym ( tmp [ 16 ] , ef9sym ) ) {
( tmp [ 17 ] = arg_0 ( tmp [ 16 ] ) ) ;
if ( check_sym ( tmp [ 17 ] , ef10sym ) ) {
( tmp [ 18 ] = arg_0 ( tmp [ 17 ] ) ) ;
if ( check_sym ( tmp [ 18 ] , lf2sym ) ) {
( tmp [ 19 ] = arg_0 ( tmp [ 18 ] ) ) ;
if ( check_sym ( tmp [ 12 ] , ef4sym ) ) {
( tmp [ 20 ] = arg_0 ( tmp [ 12 ] ) ) ;
if ( check_sym ( tmp [ 20 ] , ef5sym ) ) {
( tmp [ 21 ] = arg_0 ( tmp [ 20 ] ) ) ;
if ( not_empty_list ( tmp [ 19 ] ) ) {
if ( term_equal ( list_head ( tmp [ 19 ] ) , make_char ( 34 ) ) ) {
( tmp [ 22 ] = list_tail ( tmp [ 19 ] ) ) ;
if ( is_single_element ( tmp [ 22 ] ) ) {
if ( term_equal ( list_head ( tmp [ 22 ] ) , make_char ( 34 ) ) ) {
FUNC_EXIT ( tmp [ 21 ] ) ;
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
FUNC_EXIT ( make_nf1 ( lf_AUX_TermAsFixAccess58_1sym , arg0 ) ) ;
}
}
ATerm lf2 ( ATerm arg0 ) {
CONS_ENTRY ( lf2sym , ATmakeAppl ( lf2sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf2sym , arg0 ) ) ;
}

