/*

    Meta-Environment - An environment for language prototyping.
    Copyright (C) 2001  Stichting Mathematisch Centrum, Amsterdam, 
    The Netherlands. 

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA

*/
/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
static Symbol lf_AUX_Improve_C_code1_1sym ;
static ATerm lf_AUX_Improve_C_code1_1 ( ) ;
static Symbol lf_AUX_Improve_C_code1_2sym ;
static ATerm lf_AUX_Improve_C_code1_2 ( ATerm arg1 , ATerm arg2 ) ;
void register_AUX_Improve_C_code1 ( ) {
lf_AUX_Improve_C_code1_1sym = ATmakeSymbol ( "prod(id(\"Improve-C-code\"),w(\"\"),[ql(\"0\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"TagId\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"reject\")],w(\"\"),l(\"}\")))"
 , 0 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Improve_C_code1_1sym ) ;
lf_AUX_Improve_C_code1_2sym = ATmakeSymbol ( "prod(id(\"Improve-C-code\"),w(\"\"),[ql(\"<\"),w(\"\"),sort(\"Statement-list-opt\"),w(\"\"),ql(\"|\"),w(\"\"),sort(\"Bool\"),w(\"\"),ql(\">\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"SB-tuple\"),w(\"\"),no-attrs)" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Improve_C_code1_2sym ) ;
register_prod ( ATparse ( "prod(id(\"Improve-C-code\"),w(\"\"),[ql(\"0\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"TagId\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"reject\")],w(\"\"),l(\"}\")))" ) , lf_AUX_Improve_C_code1_1 , lf_AUX_Improve_C_code1_1sym ) ;
register_prod ( ATparse ( "prod(id(\"Improve-C-code\"),w(\"\"),[ql(\"<\"),w(\"\"),sort(\"Statement-list-opt\"),w(\"\"),ql(\"|\"),w(\"\"),sort(\"Bool\"),w(\"\"),ql(\">\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"SB-tuple\"),w(\"\"),no-attrs)" ) , lf_AUX_Improve_C_code1_2 , lf_AUX_Improve_C_code1_2sym ) ;
}
void resolve_AUX_Improve_C_code1 ( ) {
}
void init_AUX_Improve_C_code1 ( ) {
}
ATerm lf_AUX_Improve_C_code1_2 ( ATerm arg0 , ATerm arg1 ) {
CONS_ENTRY ( lf_AUX_Improve_C_code1_2sym , ATmakeAppl ( lf_AUX_Improve_C_code1_2sym , arg0 , arg1 ) ) ;
CONS_EXIT ( make_nf2 ( lf_AUX_Improve_C_code1_2sym , arg0 , arg1 ) ) ;
}
ATerm lf_AUX_Improve_C_code1_1 ( ) {
CONS_ENTRY ( lf_AUX_Improve_C_code1_1sym , ATmakeAppl0 ( lf_AUX_Improve_C_code1_1sym ) ) ;
CONS_EXIT ( make_nf0 ( lf_AUX_Improve_C_code1_1sym ) ) ;
}

