/*

    Asf Sdf Compiler Runtime Library
    Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam, 
    The Netherlands. 

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA

*/
/* This C code is generated by the AsfSdfCompiler version 1.0 */

#include  "asc-support.h"
static Symbol lf_AUX_Transform_Constructors6_3sym ;
static ATerm lf_AUX_Transform_Constructors6_3 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol ef2sym ;
static funcptr ef2 ;
static Symbol ef1sym ;
static funcptr ef1 ;
static Symbol lf_AUX_Transform_Constructors6_1sym ;
static ATerm lf_AUX_Transform_Constructors6_1 ( ATerm arg1 ) ;
static Symbol lf_AUX_Transform_Constructors6_2sym ;
static ATerm lf_AUX_Transform_Constructors6_2 ( ATerm arg1 ) ;
void register_AUX_Transform_Constructors6 ( ) {
lf_AUX_Transform_Constructors6_3sym = ATmakeSymbol ( "prod(id(\"Transform-Constructors\"),w(\"\"),[l(\"are-constructor-terms\"),w(\"\"),l(\"(\"),w(\"\"),iter-sep(l(\"{\"),w(\"\"),sort(\"Term\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"+\")),w(\"\"),l(\",\"),w(\"\"),iter-sep(l(\"{\"),w(\"\"),sort(\"NamePair\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"*\")),w(\"\"),l(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)"
 , 2 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Transform_Constructors6_3sym ) ;
lf_AUX_Transform_Constructors6_1sym = ATmakeSymbol ( "listtype(sort(\"Term\"),ql(\",\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Transform_Constructors6_1sym ) ;
lf_AUX_Transform_Constructors6_2sym = ATmakeSymbol ( "listtype(sort(\"NamePair\"),ql(\",\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Transform_Constructors6_2sym ) ;
register_prod ( ATparse ( "listtype(sort(\"Term\"),ql(\",\"))" ) , lf_AUX_Transform_Constructors6_1 , lf_AUX_Transform_Constructors6_1sym ) ;
register_prod ( ATparse ( "listtype(sort(\"NamePair\"),ql(\",\"))" ) , lf_AUX_Transform_Constructors6_2 , lf_AUX_Transform_Constructors6_2sym ) ;
register_prod ( ATparse ( "prod(id(\"Transform-Constructors\"),w(\"\"),[l(\"are-constructor-terms\"),w(\"\"),l(\"(\"),w(\"\"),iter-sep(l(\"{\"),w(\"\"),sort(\"Term\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"+\")),w(\"\"),l(\",\"),w(\"\"),iter-sep(l(\"{\"),w(\"\"),sort(\"NamePair\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"*\")),w(\"\"),l(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) , lf_AUX_Transform_Constructors6_3 , lf_AUX_Transform_Constructors6_3sym ) ;
}
void resolve_AUX_Transform_Constructors6 ( ) {
ef1 = lookup_func ( ATreadFromString ( "prod(id(\"Transform-Constructors\"),w(\"\"),[l(\"is-constructor-term\"),w(\"\"),l(\"(\"),w(\"\"),sort(\"Term\"),w(\"\"),l(\",\"),w(\"\"),iter-sep(l(\"{\"),w(\"\"),sort(\"NamePair\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"*\")),w(\"\"),l(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef1sym = lookup_sym ( ATreadFromString ( "prod(id(\"Transform-Constructors\"),w(\"\"),[l(\"is-constructor-term\"),w(\"\"),l(\"(\"),w(\"\"),sort(\"Term\"),w(\"\"),l(\",\"),w(\"\"),iter-sep(l(\"{\"),w(\"\"),sort(\"NamePair\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"*\")),w(\"\"),l(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) ) ;
ef2 = lookup_func ( ATreadFromString ( "prod(id(\"ATerm-Booleans\"),w(\"\"),[sort(\"Bool\"),w(\"\"),ql(\"/\\\\\\\\\"),w(\"\"),sort(\"Bool\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"assoc\")],w(\"\"),l(\"}\")))" ) ) ;
ef2sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerm-Booleans\"),w(\"\"),[sort(\"Bool\"),w(\"\"),ql(\"/\\\\\\\\\"),w(\"\"),sort(\"Bool\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"assoc\")],w(\"\"),l(\"}\")))" ) ) ;
}
void init_AUX_Transform_Constructors6 ( ) {
}
ATerm lf_AUX_Transform_Constructors6_3 ( ATerm arg0 , ATerm arg1 ) {
{
ATerm tmp [ 4 ] ;
FUNC_ENTRY ( lf_AUX_Transform_Constructors6_3sym , ATmakeAppl ( lf_AUX_Transform_Constructors6_3sym , arg0 , arg1 ) ) ;
if ( check_sym ( arg0 , lf_AUX_Transform_Constructors6_1sym ) ) {
{
ATerm atmp00 = arg_0 ( arg0 ) ;
if ( check_sym ( arg1 , lf_AUX_Transform_Constructors6_2sym ) ) {
{
ATerm atmp10 = arg_0 ( arg1 ) ;
if ( is_single_element ( atmp00 ) ) {
( tmp [ 0 ] = list_head ( atmp00 ) ) ;
FUNC_EXIT ( ( * ef1 ) ( tmp [ 0 ] , lf_AUX_Transform_Constructors6_2 ( make_list ( atmp10 ) ) ) ) ;
}
if ( not_empty_list ( atmp00 ) ) {
( tmp [ 0 ] = list_head ( atmp00 ) ) ;
( tmp [ 1 ] = list_tail ( atmp00 ) ) ;
if ( not_empty_list ( tmp [ 1 ] ) ) {
( tmp [ 2 ] = ( * ef1 ) ( tmp [ 0 ] , lf_AUX_Transform_Constructors6_2 ( make_list ( atmp10 ) ) ) ) ;
( tmp [ 3 ] = lf_AUX_Transform_Constructors6_3 ( lf_AUX_Transform_Constructors6_1 ( make_list ( tmp [ 1 ] ) ) , lf_AUX_Transform_Constructors6_2 ( make_list ( atmp10 ) ) ) ) ;
FUNC_EXIT ( ( * ef2 ) ( tmp [ 2 ] , tmp [ 3 ] ) ) ;
}
}
}
}
}
}
FUNC_EXIT ( make_nf2 ( lf_AUX_Transform_Constructors6_3sym , arg0 , arg1 ) ) ;
}
}
ATerm lf_AUX_Transform_Constructors6_2 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Transform_Constructors6_2sym , ATmakeAppl ( lf_AUX_Transform_Constructors6_2sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Transform_Constructors6_2sym , arg0 ) ) ;
}
ATerm lf_AUX_Transform_Constructors6_1 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Transform_Constructors6_1sym , ATmakeAppl ( lf_AUX_Transform_Constructors6_1sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Transform_Constructors6_1sym , arg0 ) ) ;
}

