/* This C code is generated by the AsfSdfCompiler version 0.1 */

#include  "asc-support.h"
void register_AUX_Trans_Set_Pats1 ( ) {
}
void resolve_AUX_Trans_Set_Pats1 ( ) {
}
void init_AUX_Trans_Set_Pats1 ( ) {
}

