/*

    Meta-Environment - An environment for language prototyping.
    Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam, 
    The Netherlands. 

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA

*/
/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
static Symbol lf_AUX_Optimize_MuASF1_1sym ;
static ATerm lf_AUX_Optimize_MuASF1_1 ( ATerm arg1 ) ;
static Symbol lf_AUX_Optimize_MuASF1_2sym ;
static ATerm lf_AUX_Optimize_MuASF1_2 ( ) ;
static Symbol lf_AUX_Optimize_MuASF1_3sym ;
static ATerm lf_AUX_Optimize_MuASF1_3 ( ) ;
static Symbol lf_AUX_Optimize_MuASF1_5sym ;
static ATerm lf_AUX_Optimize_MuASF1_5 ( ATerm arg1 ) ;
static Symbol lf_AUX_Optimize_MuASF1_4sym ;
static ATerm lf_AUX_Optimize_MuASF1_4 ( ATerm arg1 ) ;
static Symbol lf_AUX_Optimize_MuASF1_6sym ;
static ATerm lf_AUX_Optimize_MuASF1_6 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol lf_AUX_Optimize_MuASF1_7sym ;
static ATerm lf_AUX_Optimize_MuASF1_7 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol lf_AUX_Optimize_MuASF1_8sym ;
static ATerm lf_AUX_Optimize_MuASF1_8 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol lf_AUX_Optimize_MuASF1_9sym ;
static ATerm lf_AUX_Optimize_MuASF1_9 ( ATerm arg1 , ATerm arg2 ) ;
void register_AUX_Optimize_MuASF1 ( ) {
lf_AUX_Optimize_MuASF1_1sym = ATmakeSymbol ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"remove-dummy-list-ids\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Module\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Module\"),w(\"\"),no-attrs)"
 , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Optimize_MuASF1_1sym ) ;
lf_AUX_Optimize_MuASF1_2sym = ATmakeSymbol ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"unavailable\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"EmbeddingAt\"),w(\"\"),no-attrs)" , 0 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Optimize_MuASF1_2sym ) ;
lf_AUX_Optimize_MuASF1_3sym = ATmakeSymbol ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"unavailable\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"FunIdHasEmbeddingAt\"),w(\"\"),no-attrs)" , 0 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Optimize_MuASF1_3sym ) ;
lf_AUX_Optimize_MuASF1_5sym = ATmakeSymbol ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"[\"),w(\"\"),iter(sort(\"FunId\"),w(\"\"),l(\"*\")),w(\"\"),ql(\"]\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Embedding\"),w(\"\"),no-attrs)" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Optimize_MuASF1_5sym ) ;
lf_AUX_Optimize_MuASF1_4sym = ATmakeSymbol ( "listtype(sort(\"FunId\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Optimize_MuASF1_4sym ) ;
lf_AUX_Optimize_MuASF1_6sym = ATmakeSymbol ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[sort(\"Embedding\"),w(\"\"),ql(\"at\"),w(\"\"),sort(\"Int\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"EmbeddingAt\"),w(\"\"),no-attrs)" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Optimize_MuASF1_6sym ) ;
lf_AUX_Optimize_MuASF1_7sym = ATmakeSymbol ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[sort(\"FunId\"),w(\"\"),ql(\"has\"),w(\"\"),sort(\"EmbeddingAt\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"FunIdHasEmbeddingAt\"),w(\"\"),no-attrs)" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Optimize_MuASF1_7sym ) ;
lf_AUX_Optimize_MuASF1_8sym = ATmakeSymbol ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"remove-emb-side\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Term\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"FunIdHasEmbeddingAt\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Term\"),w(\"\"),no-attrs)" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Optimize_MuASF1_8sym ) ;
lf_AUX_Optimize_MuASF1_9sym = ATmakeSymbol ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"is-list-injection\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"FunId\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"NameTable\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Optimize_MuASF1_9sym ) ;
register_prod ( ATparse ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"remove-dummy-list-ids\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Module\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Module\"),w(\"\"),no-attrs)" ) , lf_AUX_Optimize_MuASF1_1 , lf_AUX_Optimize_MuASF1_1sym ) ;
register_prod ( ATparse ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"unavailable\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"EmbeddingAt\"),w(\"\"),no-attrs)" ) , lf_AUX_Optimize_MuASF1_2 , lf_AUX_Optimize_MuASF1_2sym ) ;
register_prod ( ATparse ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"unavailable\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"FunIdHasEmbeddingAt\"),w(\"\"),no-attrs)" ) , lf_AUX_Optimize_MuASF1_3 , lf_AUX_Optimize_MuASF1_3sym ) ;
register_prod ( ATparse ( "listtype(sort(\"FunId\"))" ) , lf_AUX_Optimize_MuASF1_4 , lf_AUX_Optimize_MuASF1_4sym ) ;
register_prod ( ATparse ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"[\"),w(\"\"),iter(sort(\"FunId\"),w(\"\"),l(\"*\")),w(\"\"),ql(\"]\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Embedding\"),w(\"\"),no-attrs)" ) , lf_AUX_Optimize_MuASF1_5 , lf_AUX_Optimize_MuASF1_5sym ) ;
register_prod ( ATparse ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[sort(\"Embedding\"),w(\"\"),ql(\"at\"),w(\"\"),sort(\"Int\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"EmbeddingAt\"),w(\"\"),no-attrs)" ) , lf_AUX_Optimize_MuASF1_6 , lf_AUX_Optimize_MuASF1_6sym ) ;
register_prod ( ATparse ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[sort(\"FunId\"),w(\"\"),ql(\"has\"),w(\"\"),sort(\"EmbeddingAt\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"FunIdHasEmbeddingAt\"),w(\"\"),no-attrs)" ) , lf_AUX_Optimize_MuASF1_7 , lf_AUX_Optimize_MuASF1_7sym ) ;
register_prod ( ATparse ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"remove-emb-side\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Term\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"FunIdHasEmbeddingAt\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Term\"),w(\"\"),no-attrs)" ) , lf_AUX_Optimize_MuASF1_8 , lf_AUX_Optimize_MuASF1_8sym ) ;
register_prod ( ATparse ( "prod(id(\"Optimize-MuASF\"),w(\"\"),[ql(\"is-list-injection\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"FunId\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"NameTable\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Bool\"),w(\"\"),no-attrs)" ) , lf_AUX_Optimize_MuASF1_9 , lf_AUX_Optimize_MuASF1_9sym ) ;
}
void resolve_AUX_Optimize_MuASF1 ( ) {
}
void init_AUX_Optimize_MuASF1 ( ) {
}
ATerm lf_AUX_Optimize_MuASF1_9 ( ATerm arg0 , ATerm arg1 ) {
CONS_ENTRY ( lf_AUX_Optimize_MuASF1_9sym , ATmakeAppl ( lf_AUX_Optimize_MuASF1_9sym , arg0 , arg1 ) ) ;
CONS_EXIT ( make_nf2 ( lf_AUX_Optimize_MuASF1_9sym , arg0 , arg1 ) ) ;
}
ATerm lf_AUX_Optimize_MuASF1_8 ( ATerm arg0 , ATerm arg1 ) {
CONS_ENTRY ( lf_AUX_Optimize_MuASF1_8sym , ATmakeAppl ( lf_AUX_Optimize_MuASF1_8sym , arg0 , arg1 ) ) ;
CONS_EXIT ( make_nf2 ( lf_AUX_Optimize_MuASF1_8sym , arg0 , arg1 ) ) ;
}
ATerm lf_AUX_Optimize_MuASF1_7 ( ATerm arg0 , ATerm arg1 ) {
CONS_ENTRY ( lf_AUX_Optimize_MuASF1_7sym , ATmakeAppl ( lf_AUX_Optimize_MuASF1_7sym , arg0 , arg1 ) ) ;
CONS_EXIT ( make_nf2 ( lf_AUX_Optimize_MuASF1_7sym , arg0 , arg1 ) ) ;
}
ATerm lf_AUX_Optimize_MuASF1_6 ( ATerm arg0 , ATerm arg1 ) {
CONS_ENTRY ( lf_AUX_Optimize_MuASF1_6sym , ATmakeAppl ( lf_AUX_Optimize_MuASF1_6sym , arg0 , arg1 ) ) ;
CONS_EXIT ( make_nf2 ( lf_AUX_Optimize_MuASF1_6sym , arg0 , arg1 ) ) ;
}
ATerm lf_AUX_Optimize_MuASF1_4 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Optimize_MuASF1_4sym , ATmakeAppl ( lf_AUX_Optimize_MuASF1_4sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Optimize_MuASF1_4sym , arg0 ) ) ;
}
ATerm lf_AUX_Optimize_MuASF1_5 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Optimize_MuASF1_5sym , ATmakeAppl ( lf_AUX_Optimize_MuASF1_5sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Optimize_MuASF1_5sym , arg0 ) ) ;
}
ATerm lf_AUX_Optimize_MuASF1_3 ( ) {
CONS_ENTRY ( lf_AUX_Optimize_MuASF1_3sym , ATmakeAppl0 ( lf_AUX_Optimize_MuASF1_3sym ) ) ;
CONS_EXIT ( make_nf0 ( lf_AUX_Optimize_MuASF1_3sym ) ) ;
}
ATerm lf_AUX_Optimize_MuASF1_2 ( ) {
CONS_ENTRY ( lf_AUX_Optimize_MuASF1_2sym , ATmakeAppl0 ( lf_AUX_Optimize_MuASF1_2sym ) ) ;
CONS_EXIT ( make_nf0 ( lf_AUX_Optimize_MuASF1_2sym ) ) ;
}
ATerm lf_AUX_Optimize_MuASF1_1 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Optimize_MuASF1_1sym , ATmakeAppl ( lf_AUX_Optimize_MuASF1_1sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Optimize_MuASF1_1sym , arg0 ) ) ;
}

