/**
 * This file is generated by tifstoc. Do not edit!
 * Generated from tifs for tool 'ptpretty' (prefix='')
 * Headerfile generated at Thu Sep 18 09:16:14 2003
 */

#ifndef _PTPRETTY_H
#define _PTPRETTY_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
ATerm format(int conn, ATerm, ATerm);
void rec_terminate(int conn, ATerm);
extern ATerm ptpretty_handler(int conn, ATerm term);
extern ATerm ptpretty_checker(int conn, ATerm sigs);

#endif
