/**
 * This file is generated by tifstoc. Do not edit!
 * Generated from tifs for tool 'sglr' (prefix='')
 * Headerfile generated at Mon Jan 12 17:40:09 2004
 */

#ifndef _SGLR_H
#define _SGLR_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
ATerm open_language(int conn, ATerm, ATerm);
ATerm parse_string(int conn, ATerm, char *, char *);
void rec_terminate(int conn, ATerm);
extern ATerm sglr_handler(int conn, ATerm term);
extern ATerm sglr_checker(int conn, ATerm sigs);

#endif
