/*

    Meta-Environment - An environment for language prototyping.
    Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam, 
    The Netherlands. 

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA

*/
/* This C code is generated by the AsfSdfCompiler version 1.2 */

#include  "asc-support.h"
static Symbol lf_AUX_Add_Prefer_Variables2_2sym ;
static ATerm lf_AUX_Add_Prefer_Variables2_2 ( ATerm arg1 ) ;
static Symbol ef2sym ;
static funcptr ef2 ;
static Symbol ef1sym ;
static funcptr ef1 ;
static Symbol lf_AUX_Add_Prefer_Variables2_1sym ;
static ATerm lf_AUX_Add_Prefer_Variables2_1 ( ATerm arg1 ) ;
void register_AUX_Add_Prefer_Variables2 ( ) {
lf_AUX_Add_Prefer_Variables2_2sym = ATmakeSymbol ( "prod(id(\"Add-Prefer-Variables\"),w(\"\"),[ql(\"add-prefer-vars\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"Module\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Definition\"),w(\"\"),no-attrs)"
 , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Add_Prefer_Variables2_2sym ) ;
lf_AUX_Add_Prefer_Variables2_1sym = ATmakeSymbol ( "listtype(sort(\"Module\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Add_Prefer_Variables2_1sym ) ;
register_prod ( ATparse ( "listtype(sort(\"Module\"))" ) , lf_AUX_Add_Prefer_Variables2_1 , lf_AUX_Add_Prefer_Variables2_1sym ) ;
register_prod ( ATparse ( "prod(id(\"Add-Prefer-Variables\"),w(\"\"),[ql(\"add-prefer-vars\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"Module\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Definition\"),w(\"\"),no-attrs)" ) , lf_AUX_Add_Prefer_Variables2_2 , lf_AUX_Add_Prefer_Variables2_2sym ) ;
}
void resolve_AUX_Add_Prefer_Variables2 ( ) {
ef1 = lookup_func ( ATreadFromString ( "prod(id(\"Modular-Sdf-Syntax\"),w(\"\"),[iter(sort(\"Module\"),w(\"\"),l(\"*\"))],w(\"\"),l(\"->\"),w(\"\"),sort(\"Definition\"),w(\"\"),no-attrs)" ) ) ;
ef1sym = lookup_sym ( ATreadFromString ( "prod(id(\"Modular-Sdf-Syntax\"),w(\"\"),[iter(sort(\"Module\"),w(\"\"),l(\"*\"))],w(\"\"),l(\"->\"),w(\"\"),sort(\"Definition\"),w(\"\"),no-attrs)" ) ) ;
ef2 = lookup_func ( ATreadFromString ( "prod(id(\"Add-Prefer-Variables\"),w(\"\"),[ql(\"add-pv-for-modules\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"Module\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Definition\"),w(\"\"),no-attrs)" ) ) ;
ef2sym = lookup_sym ( ATreadFromString ( "prod(id(\"Add-Prefer-Variables\"),w(\"\"),[ql(\"add-pv-for-modules\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"Module\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Definition\"),w(\"\"),no-attrs)" ) ) ;
}
void init_AUX_Add_Prefer_Variables2 ( ) {
}
ATerm lf_AUX_Add_Prefer_Variables2_2 ( ATerm arg0 ) {
{
ATerm tmp [ 3 ] ;
FUNC_ENTRY ( lf_AUX_Add_Prefer_Variables2_2sym , ATmakeAppl ( lf_AUX_Add_Prefer_Variables2_2sym , arg0 ) ) ;
if ( check_sym ( arg0 , lf_AUX_Add_Prefer_Variables2_1sym ) ) {
{
ATerm atmp00 = arg_0 ( arg0 ) ;
( tmp [ 0 ] = ( * ef2 ) ( lf_AUX_Add_Prefer_Variables2_1 ( make_list ( atmp00 ) ) ) ) ;
if ( check_sym ( tmp [ 0 ] , ef1sym ) ) {
( tmp [ 1 ] = arg_0 ( tmp [ 0 ] ) ) ;
if ( check_sym ( tmp [ 1 ] , lf_AUX_Add_Prefer_Variables2_1sym ) ) {
( tmp [ 2 ] = arg_0 ( tmp [ 1 ] ) ) ;
FUNC_EXIT ( ( * ef1 ) ( lf_AUX_Add_Prefer_Variables2_1 ( make_list ( tmp [ 2 ] ) ) ) ) ;
}
}
}
}
FUNC_EXIT ( make_nf1 ( lf_AUX_Add_Prefer_Variables2_2sym , arg0 ) ) ;
}
}
ATerm lf_AUX_Add_Prefer_Variables2_1 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Add_Prefer_Variables2_1sym , ATmakeAppl ( lf_AUX_Add_Prefer_Variables2_1sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Add_Prefer_Variables2_1sym , arg0 ) ) ;
}

