#!/bin/sh

VERSION=0.1.1

usage() {
   cat <<ENDCAT
usage: $0

All .eqs.tbl files and
all .asf.baf files and
all .eqs.baf files in the current directory will be removed.
All .eqs files in the current directory will be moved to .asf files.

NOTE: running this script in the same directory twice will have unwanted
      results!!
ENDCAT
}

version() {
   cat <<ENDCAT
$0 version $VERSION
ENDCAT
}


while getopts hV c
do
   case $c in
      h) usage; exit 0 ;;
      V) version; exit 0 ;;
      *) usage ; exit 1;;
   esac
done

rm *.eqs.tbl
rm *.asf.baf
rm *.eqs.baf

for i in *.eqs; do
  mv $i `basename $i .eqs`.asf
done


