#!/bin/sh

VERSION=0.1.1

usage() {
   cat <<ENDCAT
usage: $0

All .eqs files in the current directory will be moved to .asf files.
All .eqs.tbl files in the current directory will be moved to .asf.tbl files.
All .asf.baf files in the current directory will be moved to .eqs files.
All .eqs.baf files in the current directory will be moved to .asf.baf files.

NOTE: running this script in the same directory twice will have unwanted
      results!!
ENDCAT
}

version() {
   cat <<ENDCAT
$0 version $VERSION
ENDCAT
}


while getopts hV c
do
   case $c in
      h) usage; exit 0 ;;
      V) version; exit 0 ;;
      *) usage ; exit 1;;
   esac
done

for i in *.eqs; do
  mv $i `basename $i .eqs`.asf
done

for i in *.asf.baf; do
  mv $i `basename $i .asf.baf`.eqs
done

for i in *.eqs.baf; do
  mv $i `basename $i .eqs.baf`.asf.baf
done

for i in *.eqs.tbl; do
  mv $i `basename $i .eqs.tbl`.asf.tbl
done
