#! /bin/sh
#
#    Meta-Environment - An environment for language prototyping.
#    Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam, The Netherlands. 
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#

usage () { 
	echo "Usage: $1 <program-under-test>"
	exit 0
}
	
if [ $# != 1 ]; then
  usage $0
fi

if [ $1 = "-h" -o $1 = "--help" ]; then 
  usage $0
fi

output=`$1 -h 2>&1`
result=$?

if [ $result != 0 ]; then
	echo "$1 -h returned $result result"
	exit 1
fi

if echo $output | grep -i usage >/dev/null; then
	exit 0
else
  echo "$1 -h does not return \"usage\"";
  exit 1
fi

